### ISSUE TITLE
Autofixture with AutoNSubstitute fails with NSubstitute 3.10

### ISSUE THREAD

**Issue by OsirisTerje** [AutoFixture/AutoFixture#1002]
I am using Autofixture with NSubstitute 3.10, but lately gets error when it runs giving the exception below:

Inner exception messages:
	System.IO.FileLoadException: Could not load file or assembly 'NSubstitute, Version=2.0.3.0, Culture=neutral, PublicKeyToken=92dd2e9066daa5ca' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

In the bin folder I see that the NSubstitute dll (3.10) are present together with the AutoFixture dlls, and according to the range for AutoFixture is shoudl work with 3.10. 

This happens with VS 2017 15.6.1, using the new csproj format - not sure if that is relevant at all, but it all worked with the older csproj format, and earlier versions of VS2017

**Comment by OsirisTerje** [comment]
Adding the following binding redirect solved the issue for now, but it should not have been necessary:
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
    <assemblyIdentity name="NSubstitute"
                      publicKeyToken="92dd2e9066daa5ca"
                      culture="neutral" />

    <bindingRedirect oldVersion="2.0.3.0" newVersion="3.1.0.0" />
  </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by zvirja** [comment]
@OsirisTerje This is totally fine that we target the older version of `NSubstitute`. It should work because of the binding redirection. Try adding the following attributes to your `csproj` file:
```xml
<PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```

See more detail: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

Closing this as no actions are required from our side. 
Thanks again for registering the issue. Let me know if you still observe troubles after applying the suggested changes.
