### ISSUE TITLE
NSubstitute.ReceivedCalls() returning wrong value using AutoFixture.AutoNSubstitute

### ISSUE THREAD

**Issue by dklinger** [AutoFixture/AutoFixture#1007]
We have a lot of tests using 'Class.ReceivedCalls()' and 'var tmp = Class.Received(int).Property;' to check the call count. In v3 of AutoFixture it correctly reported the call count, especially of Properties, which it doesn't do anymore. The call count of methods seems to be still ok.
Given that we have the following code:
```csharp
    public interface IRunSpeed
    {
        int Speed { get; }
    }

    public class GetToDaChoppa
    {
        private readonly IRunSpeed _runSpeed;

        public GetToDaChoppa(IRunSpeed runSpeed)
        {
            _runSpeed = runSpeed ?? throw new ArgumentNullException(nameof(runSpeed));
        }

        public void DoItNow()
        {
            var runningSpeed = _runSpeed.Speed;
        }
    }
```
And given that we have the following tests:
```csharp
        [Fact]
        public void DoItNow_WithOutAutoNSubstitute()
        {
            // Arrange
            var runSpeed = Substitute.For<IRunSpeed>();
            runSpeed.Speed.Returns(2);

            var sut = new GetToDaChoppa(runSpeed);

            //Act
            sut.DoItNow();

            //Assert
            var tmp = runSpeed.Received(1).Speed;
            Assert.Single(runSpeed.ReceivedCalls());
        }

        [Theory, AutoNSubstituteData]
        public void DoItNow_UsingAutoNSubstitute(
            [Frozen] IRunSpeed runSpeed,
            GetToDaChoppa sut)
        {
            // Arrange
            runSpeed.Speed.Returns(49);

            //Act
            sut.DoItNow();

            //Assert
            var tmp = runSpeed.Received(1).Speed;
            Assert.Single(runSpeed.ReceivedCalls());
```

My AutoNSubstituteDataAttribute looks like this:
```csharp
        public class AutoNSubstituteDataAttribute : AutoDataAttribute
        {
            public AutoNSubstituteDataAttribute()
                : base(() => new Fixture()
                           .Customize(new AutoNSubstituteCustomization()))
            {
            }
        }
```
The first test 'DoItNow_WithOutAutoNSubstitute' is working fine. But the second test 'DoItNow_UsingAutoNSubstitute' returns 2 for 'ios.Received(1).Speed;'.
It also returns 2 for 'runSpeed.ReceivedCalls();'.
Because of this we currently cannot upgrade our Solutions to v4 as we instantly have >1000 failing tests per solution. Any guidance on what the problem might be or where to look for the fix?

**Comment by zvirja** [comment]
Thanks for firing the issue. Actually, this issue has nothing to do with AutoFixture, while we are affected by it as well 😕

This issue is mostly caused by xUnit and if you rewrite the test as following, it will pass:
```c#
[Theory, AutoNSubstituteData]
public void DoItNow_UsingAutoNSubstitute_CreateManually(IFixture fixture)
{
    // Arrange
    var runSpeed = fixture.Freeze<IRunSpeed>();
    var sut = fixture.Create<GetToDaChoppa>();
    runSpeed.Speed.Returns(49);

    //Act
    sut.DoItNow();

    //Assert
    var tmp = runSpeed.Received(1).Speed;
    Assert.Single(runSpeed.ReceivedCalls());
}
```

When you run tests, xUnit tries to format the test name for you. If it finds that type is not known and doesn't have `ToString()` overload, it uses the structural inspection and recursively fetches the property values. If you check the test name, you'll see the following:
![image](https://user-images.githubusercontent.com/1074182/38032882-5a2bc820-32a7-11e8-9159-fd278ae59357.png)

As you might notice, xUnit fetched the `Speed` property value to nicely show you the test argument. As this is a usual invocation, NSubstitute counted that as a call.

It's quite strange that you didn't have this issue with v3, as nothing changed in that regards. I've just tested xUnit2 + `AutoFixture v3` and still got the issue. Probably, you have upgraded the xUnit as well.

----

As for a workaround, I have good and bad news. The good news is that this will be resolved in the next major version of NSubsitute, as it started to override the `ToString()` method to return a proxy id. As result, xUnit doesn't touch the properties anymore:
![image](https://user-images.githubusercontent.com/1074182/38033166-12f437fc-32a8-11e8-9ca5-b6278561972b.png)

The bad news is that NSubsitute v4 has not been released yet.

I could suggest you either:
- postpone migration till NSubsitute v4 is released;
- use the latest `master` source code of NSubsitute, make a local build and use your own `NSubsitute.dll` instead of NuGet package. After v4 is released, you can switch to the NuGet package.
- if you updated xUnit version as well (as this might explain why you didn't have this issue before), revert that change and use the previous version of xUnit.

I apologize for the inconvenience, but, unfortunately, we can do nothing on AutoFixture side to fix this issue.

**Comment by evilbaschdi** [comment]
just tested this. finally our tests asserting ReceivedCalls went back to have a successful result again.
Something that still fails are the asserts on Received(x) like Received(1).Speed Daniel mentioned above.

Do you also have an answer / solution for hat?

**Comment by zvirja** [comment]
Are you guys working on the same project? :) If so, could you clarify how you fixed the issue?

The options suggested above should help with both the issues. If they don't - clarify the scenario.

**Comment by evilbaschdi** [comment]
not actually the same project but at the same company.
we've been on xunit 1.9 + nsubstitute 2 / 3 for a long time and finally managed it to get our internal assemblies (nuget packages so a simple way back to an older version of just one reference is not as much as easy as it sounds to be) to be compatible to xunit2. and now we have these two problems.

We already tried out some things and finally thought it must have something to do with autofixture - because of the frozen-attribute and a hard coded test execution count - or something like that.
after daniel opened this case he postet me the link to it.

just as you described above I replaced the nuget 3.1 reference with the one from the fresh compiled nsubstitute project. after that I now have 118 instead of 178 failing tests because of Receiced(x) is still evaluating the wrong number of calls.

my project is currently based on .net 4.5.2 with xunit2, current repo version of nsubstitute and autofixture 4.2 referenced. all of the tests are failing for the same two reasons - also there are still some receivedcalls failing in the unit tests.
I think I have to have a deeper look into it again when I'm back to the office again (out for easter).
maybe @dklinger meanwhile can describe the scenario.

**Comment by zvirja** [comment]
@dklinger @evilbaschdi Please follow up after you have a chance to check that - it's quite interesting why you sill see the issues, even after you applied the patch.

Re-open the issue to indicate that we still have ongoing investigation.

**Comment by dklinger** [comment]
Ok, so I've tested the last few hours. First: Thanks for your reply, your explanation and the suggestions - that helped a lot.
I've tested v4 of NSubstitute. It works for my example code above, but does not resolve the issue entirely in our real world projects. The issue is, that it resolves the problem of the wrong ReceivedCalls-count only for SUT-Calls to methods, not to properties.

Example of our now working code:
```csharp
        [Theory, AutoNSubstituteData]
        public void DoItNow_UsingAutoNSubstitute(
            [Frozen] IRunSpeed runSpeed,
            GetToDaChoppa sut)
        {
            // Arrange
            runSpeed.Speed.Returns(49);

            //Act
            sut.DoItNow();

            //Assert
            var tmp = runSpeed.Received(1).Speed;
            Assert.Equal(1, runSpeed.ReceivedCalls().Count());
        }
```

But if I change the method "GetToDaChoppa.DoItNow();" to be a property "GetToDaChoppa.DoItNow" the ReceivedCallsCount is +1 again:
```csharp
        [Theory, AutoNSubstituteData]
        public void DoItNow_UsingAutoNSubstitute(
            [Frozen] IRunSpeed runSpeed,
            GetToDaChoppa sut)
        {
            // Arrange
            runSpeed.Speed.Returns(49);

            //Act
            var x = sut.DoItNow;

            //Assert
            var tmp = runSpeed.Received(1).Speed;
            Assert.Equal(1, runSpeed.ReceivedCalls().Count());
        }
```

I think it again has to do with the xUnit naming as we get this one for the working method-implementation:
![image](https://user-images.githubusercontent.com/2249766/38093866-8250cc5e-336c-11e8-883a-d975ccccf916.png)

And that one for the non-working property-implementation:
![image](https://user-images.githubusercontent.com/2249766/38093819-62b45410-336c-11e8-8073-a195207299e4.png)

It looks like xUnit is calling the SUT-property to retrieve its value to use it for the test-name but it is not doing this for SUT-methods. My first thought was that it has to do with the return value of our method "GetToDaChoppa()" which was void. But even after changing it to be "public int GetToDaChoppa()" xUnit is still not calling it to get a return value for the test Name. It is only a problem using properties.

For now I am stuck again. I totallly agree that this is not an issue of AutoFixture. But in your opinion, knowing all of the packets better than we do, what would be your suggestion?
- opening an issue for NSubstitute?
- opening an issue for xUnit2?
- or something totally new?

**Comment by zvirja** [comment]
@dklinger Thanks for the follow-up! Could you please share [MCVE](https://stackoverflow.com/help/mcve) of code for the last scenario that still fails? Just to ensure that nothing is missed and I haven't misunderstood the conditions.

After that I'll try to investigate why that happens and how to work around that.

Thanks.

**Comment by dklinger** [comment]
Yep, sure. Here it is:

System under Test:
```csharp
    public interface IRunSpeed
    {
        int Speed { get; }
        void Dude();
        int Dude2();
    }

    public class GetToDaChoppa
    {
        private readonly IRunSpeed _runSpeed;

        public GetToDaChoppa(IRunSpeed runSpeed)
        {
            _runSpeed = runSpeed ?? throw new ArgumentNullException(nameof(runSpeed));
        }

        public int DoItNow
        {
            get
            {
                var runningSpeed = _runSpeed.Speed;
                return 0;
            }
        }
    }
```

Test-Case:
```csharp
        [Theory, AutoNSubstituteData]
        public void DoItNowAsProperty_UsingAutoNSubstitute(
            [Frozen] IRunSpeed runSpeed,
            GetToDaChoppa sut)
        {
            // Arrange
            runSpeed.Speed.Returns(49);

            //Act
            var x = sut.DoItNow;

            //Assert
            var tmp = runSpeed.Received(1).Speed;
            Assert.Equal(1, runSpeed.ReceivedCalls().Count());
        }
```
Currently I'm trying to catch up on the discussions at https://github.com/xunit/xunit/issues/1386 and https://github.com/AutoFixture/AutoFixture/issues/805. Maybe we're doing something wrong or there is a way to tell xUnit to not autogenerate the test name.
I also tried to create my own TheoryAttribute overriding the DisplayName property but that does not help either as xUnit is in some way still using the autogenerated name internally. But that's just fyi and totally unrelated to the demo-code above.
```csharp
        public sealed class MyTheoryAttribute : TheoryAttribute
        {
            public MyTheoryAttribute([CallerMemberName] string memberName = null)
            {
                DisplayName = "MyTestCase";
            }
        }
```
![image](https://user-images.githubusercontent.com/2249766/38096551-6a5d3b58-3373-11e8-9893-35e51f323c82.png)

**Comment by dklinger** [comment]
Hello, me again :)
It is indeed xUnit2 calling all Properties and Fields of test-method-parameters which are of a Complex Type. The line of code is this one: https://github.com/xunit/assert.xunit/blob/2b70a9b0c5bb291f98472ec24cec437acf8d65c8/Sdk/ArgumentFormatter.cs#L156

Thanks for your support. I've reopend an issue at the xUnit-Repo where the discussion should  go on: https://github.com/xunit/xunit/issues/243
