### ISSUE TITLE
Expect random number but everytime is the same with Nunit

### ISSUE THREAD

**Issue by mrtylerzhou** [AutoFixture/AutoFixture#1041]
```cs
       [Test]
        [Repeat(10)]
        [AutoData]
        public void TestIt(int a,int b)
        {
            Assert.Positive(a + b);
        }
```
I use repeat attribute to let the method run 10 times,and I expect each time both a and b have different values but I got  the same value 10 times.

**Comment by Sobieck** [comment]
I'm getting the same results with this test code.

``` C#
using AutoFixture.NUnit3;
using FluentAssertions;
using NUnit.Framework;
using System.Collections.Generic;

namespace UnitTestProject1
{
    [TestFixture]
    public class UnitTest1
    {
        private List<int> usedInts = new List<int>();
            
        [Test]
        [Repeat(10)]
        [AutoData]
        public void TestIt(int a, int b)
        {
            usedInts.Should().NotContain(a);
            usedInts.Should().NotContain(b);
            usedInts.Add(a);
            usedInts.Add(b);
        }
    }
}
```

**Comment by zvirja** [comment]
Thanks guys for raising the issue.

I'm not using NUnit (prefer xUnit), so I don't have experience with this attribute at all. But according to [the documentation](https://github.com/nunit/docs/wiki/Repeat-Attribute) it looks like an expected behavior. Could you please describe why you expect to have different input for each run?

cc @Kralizek as NUnit user - please share your opinion as well 😉

**Comment by Kralizek** [comment]
I never used the said attribute. But I agree, from the documentation you linked it would seem that the nunit execution engine would store the parameters used for the first execution.

**Comment by zvirja** [comment]
> to increase the randomness of test.

Well, it's more about the desirable behavior, rather than explanation that current behavior is incorrect 😉 

If you wish, you could easily implement your own `AutoData` attribute that will have e.g. `Repeat` property. Use the [existing implementation](https://github.com/AutoFixture/AutoFixture/blob/b9a3f4d3962d9213546c1623f994b9a73aebd2d1/Src/AutoFixture.NUnit3/AutoDataAttribute.cs#L79) as a base.

Please let me know if you need my further assistance.

**Comment by mrtylerzhou** [comment]
thank you for you suggestion,I'll have a try
