### ISSUE TITLE
InlineAutoData Isn't Following XUnit Serialization of Params for Visual Studio test runner

### ISSUE THREAD

**Issue by CreepyGnome** [AutoFixture/AutoFixture#1048]
Currently, if I use InlineData from XUnit the Visual Studio test runner will put all the ones of theory nest under the test and you can expand and see each one's results. If I use InlineAutoData and that is the only change then that very nice feature goes away. Doing some research this is explained by Brad Wilson why and what is required by XUnit to support this feature and when it doesn't work why it isn't working.

So I think you would have to do something similar in order to make it work.  It is all explained here in this XUnit issue:

https://github.com/xunit/xunit/issues/1473

You can take any Theory that has InlineData that takes any of the supported types that make the feature work (ie: char, string, byte, short, ushort, int, uint, long, ulong, double, decimal, bool, DateTime, DateTimeOffset.  There is an example of code in that issue above as well.

This is a very nice feature in Visual Studio's Test Runner I hope you can fix this in your side as I am removing AutoFixture from places where it was only doing a simple string or and nothing complex as I rather have the expanding node on the test.

**Comment by zvirja** [comment]
Thanks for raising the issue 👍 

I do understand the reasons behind the behavior you describe and it's very unlikely we can do something about that. The reason is more global and is not directly related to the mentioned issue.

AutoFixture data attributes (`AutoData`, `InlineAutoData`) are a tool to generate dynamic parameter values for tests. Each invocation generates a unique set of values, so it's currently impossible to run test twice with the same dynamic parameter values. Some tests runners (including VS) use two phases to work with tests - discovery and actual run. If you look at `InlineData`, its values are static and cannot change between the discovery and run. On other hand, if you try to discover tests for e.g. `AutoData`, values will constantly change between discovery and run and runner will be unable to match the test to run. To support such scenarios xUnit offers a way to disable the discovery enumeration for theory, so test parameters are not read. Rather the whole theory (with all cases) is treated as a single entity and all cases are run together. Search for the `DisableDiscoveryEnumeration` parameter to get more info.

AutoFixture uses the mentioned way as well and disables discovery for the `AutoData` and `InlineAutoData` attributes. See e.g. here:
https://github.com/AutoFixture/AutoFixture/blob/d3e14a818b933d948ea82464b197a5aeb152f070/Src/AutoFixture.xUnit2/AutoDataAttribute.cs#L17-L24

In theory we could improve [our logic](https://github.com/AutoFixture/AutoFixture/blob/d3e14a818b933d948ea82464b197a5aeb152f070/Src/AutoFixture.xUnit2/NoPreDiscoveryDataDiscoverer.cs#L19) to allow enumeration for `InlineAutoData` attribute when number of specified arguments _is equal_ to the number of parameters, but I'm very reluctant to do that:
- it's very rare case when you use `InlineAutoData` instead of `InlineData` - what's the value? 😉 
- usually you don't use `InlineAutoData` in own projects, but create a custom attribute with customized fixture. Therefore, the attribute type will be different and our fix will still do nothing.
- it makes things harder to maintain.
- it's VS runner specific, so it might be improved there in further versions. For instance R# renders the stuff nicely after the run:
![image](https://user-images.githubusercontent.com/1074182/41238745-57ae12f0-6d9f-11e8-80fa-e7db9c056051.png)

Given that I don't see what can be done at our side. If you see - please suggest 😅

**Comment by zvirja** [comment]
Closing this one due to inactivity. Feel free to re-open the issue if you believe that change from our side is required.

**Comment by CreepyGnome** [comment]
Well, XUnit was able to solve the problem, and it is difficult to monitor unit tests and to be able to introduce new people to testing and showing them Theory based testing when it's really difficult to know which "data"  based test in a theory has failed.  I have to halt new uses of AutoFixture.

I feel did suggest a way, the way XUnit solved the same problem and which works perfectly and if I remove autofixture the theory unit test expands to show each "data" element as a test with a result broken out. If I place autofixture  back it goes away. So clearly it is autofixtures problem to fix and one that existed in XUnit until it was addressed by the issue I provided. Seems like either you want to fix it and can try what XUnit did and if it doesn't find a way to do it as it clearly is based on how and what types can be represented to the underlying MS testing hooks.

I don't have times to do more research for you that I already did, as it is far easier to stop adding autofixture and remove over time than it is to find the time to figure out an open source projects code and debug and figure out the solution and make a PR. I wanted to make you aware of the issue and point you to a possible solution since XUnit had the exact same issue and they solved it. It is now in the project maintainers and other contributors hands to decide if they want to solve the issue or not, not in the one reporting it.  

You have a good side community of contributors and posting an issue to the group to see if anyone is willing to take it on seems simple and worth doing than just closing down the problem and ignoring it. The worse that happens is no one takes it on with the possibility that someone will and solve it.

**Comment by zvirja** [comment]
I do fully understand your concerns and the difficulties you have! But let's have the full overview of the issue (in addition to what I already posted here).

> I feel did suggest a way, the way XUnit solved the same problem ...
> Seems like either you want to fix it and can try what XUnit did ...
> ... since XUnit had the exact same issue and they solved it.

In fact, xUnit __hasn't__ solved this problem and suffers from it as well. The reason why you don't meet it is that you mostly work with data which is constant and supports enumeration. Consider the following sample with _pure_ xUnit (notice the `DisableDiscoveryEnumeration = true` part):
```c#
    public static TheoryData<int> TestValues => new TheoryData<int> {1, 2, 3};

    [Theory]
    [MemberData(nameof(TestValues), DisableDiscoveryEnumeration = true)]
    public void PureXUnit(int primitiveValue)
    {
      Assert.NotEqual(0, primitiveValue);
    }
```
Execution result:
![image](https://user-images.githubusercontent.com/1074182/41852988-4dfde5ea-7895-11e8-9591-6e8cd02307c3.png)

As you can see, run values are not displayed even with _pure_ xUnit. AutoFixture uses the same approach under the hood (disabled enumeration), so that's why you don't see any values as well.

> Theory based testing when it's really difficult to know which "data" based test in a theory has failed. I have to halt new uses of AutoFixture.

Before making the final decision ensure that you haven't missed the following window:
![image](https://user-images.githubusercontent.com/1074182/41853475-83dc2dec-7896-11e8-86ce-23df6c2c219e.png)

If you select the failed test you can see the values used for this run (in the window below). It's probably not that convenient as inline values, however it's fully usable. If that's a deal breaker for you, you might change your opinion 😉 

FWIW if you use an alternative runner (like R#), you will get this feature out of the box.

>  worth doing than just closing down the problem and ignoring it.

Usually I try to not close the issue if I see any actions we could make to improve the situation In this particular I see _nothing reasonable_ we can do about it:
- pure xUnit suffers from it as well;
- there is already a way to see run values, so issues is not _critical_.

**Comment by CreepyGnome** [comment]
I am confused xUnit did solve the ISSUE I am having as using the only xUnit attributes it all works fine if I stick with the supported types, and when I use AutoFixture it stops working. SO the issue I HAVE REPORTED has been fixed by xUnit and I only wish AutoFixture to support the same types in the same way.

I know for a FREAKING  (choose your own expletive)  FACT THIS ISSUE IS UNDER AUTOFIXTURES CONTROL and you are choosing to deflect it and say essentially "Not my problem" because either you do not understand the issue I am have presented or you don't see it as an issue or you don't care. 

Either way, I give up as this is freaking (choose your own expletive) frustrating. So AutoFixture can fix it or don't I am done and decided to drop AutoFixture all together as its not worth the trouble when reporting bugs to have to work this hard to get people to just accept the facts. I can risk the next bug I may need to report having the same red tape.  So the issue is closed it can stay closed and I have unsubscribed.

**Comment by zvirja** [comment]
@CreepyGnome Despite the fact you decided to opt-out from the discussion, I still want to bring the clarity into this thread. I'm under the strong impression that we misunderstood each other and are speaking about different scenarios.

I see 3 potential scenarios to consider:
```c#
// Scenario 1. We are using xUnit's InlineData to specify _all_ the theory parameters.
// Notice, all the parameters are static.
[Theory]
[InlineData(42, "42")]
public void Scenario1(int number, string str)
{
    Assert.Equal(number.ToString(), str);
}

// Scenario 2. We are using AutoFixture's InlineAutoData to specify _all_ the theory parameters.
// Notice, all the parameters are static.
[Theory]
[InlineAutoData(42, "42")]
public void Scenario2(int number, string str)
{
    Assert.Equal(number.ToString(), str);
}

// Scenario 3. We are using AutoFixture's InlineAutoData to specify _only part_ of the theory parameters.
// Notice, 'str' parameter is generated dynamically during each invocation.
[Theory]
[InlineAutoData(42)]
public void Scenario3(int number, string str)
{
    Assert.Equal(number.ToString(), str);
}
```

The issue you describe in this thread sounds: "If I follow the scenario 1 I can see all the theory cases in the VS Tests tree. If I switch to the scenario 2, theory cases are no longer rendered in the tree. Please fix."

First of all please pay attention that `InlineAutoData` __is not__ a replacement for the `InlineData` and __should not__ be used instead of it whenever possible. If all the test parameters _are static_, you __should__ use the `InlineData`. It indeed offers slightly better runner experience and likely slightly better performance.

The `InlineAutoData` __should only__ be used in Scenario 3 - when part of your theory parameters are fixed, but other part is dynamically generated by AutoFixture. The `InlineAutoData` attribute is designed and optimized for such scenarios only.

The `InlineAutoData` attribute __is not__ optimized for the Scenario 2 as it brings no benefit there. Technically it could be used and will work fine, but you'll observe the inconveniences mentioned in this thread.

-------
Given that `InlineAutoData` is designed for Scenario 3, we __explicitly disabled__ the theory discovery. Otherwise, you will be unable to run the tests after the discovery. As result you observe that theory cases are not rendered in the tree. To be clear: there is __NO WAY__ to fix the tree issue and support the Scenario 3 in the same time.

As for the Scenario 2. Technically we could improve the `InlineAutoData` to support the Scenario 2 and show data in the tree if you explicitly specified __all__ the theory parameters. However, that will be super complicated and brings no benefit:
- if all the parameters are constant you are free to use `InlineData` attribute;
- very often you don't use `InlineAutoData` directly in your projects, because you want to globally customize the `fixture` (e.g. to enable `Moq`/`NSubstitute` integration). To achieve that you create your own type of this attribute, like `InlineAutoNSubstituteData` inherited from the `InlineAutoData` (or not inherited, it's not required). In this case _there is no way_ to reliably detect whether you specified all the parameters or not - custom attribute might have different signature. Therefore, this feature will work only in limited number of cases - it doesn't worth it.

Therefore, you were right - we can __partially__ solve the issue. But there is no practical sense to do that. If you wish, I could provide you with instructions and you'll do that in your project locally 😉 

----

Given all the information above in head I closed the issue, as there is no way to solve it and still support Scenario 3 - the __primary__ scenario.

Sorry if you were confused by the poor/absent documentation describing this. I'm already working on the doc site where all such things are going to be described.

Have a good day!

-----

P.S. Please do not ignore the fact that __you can see__ the actual invocation parameters as mentioned [here](https://github.com/AutoFixture/AutoFixture/issues/1048#issuecomment-399958272), so issue isn't that critical. However, of course, it's a matter of your priorities and if AutoFixture doesn't bring the benefits to your project - feel free to get rid of it 😉

**Comment by R0boC0p** [comment]
How many years later and this hasn't been addressed? 
I do understand @CreepyGnome  frustration as I just brought - for some ledgit reasons - our tests running with NUnit to the XUnit.
Now we figured, that all of our parameterized tests are showing as a single one under the Visual Studio test explorer. The test summary is showing the data used, plus which data failed/succeeded.

@zvirja Unfortunately I must also disagree with you, as you didn't consider this:

```c#
[Theory]
[CustomInlineAutoData(42)]
public void Scenario3(int number, string str, IFixture f)
{
    Assert.Equal(number.ToString(), str);
   f.Create<MyService>(); // setup in the CustomInlineAutoData
}
```

`CustomInlineAutoData` customizes the Autofixture internally and also fixes 42 for the parameter `number`. I would want to have both worlds combined, like I did with NUnit package until now. 
This is a big back-lash for me, and makes me wanna think if using xunit was the right choice.

Are there any known workarounds? Do I need to make my own `InlineAutoDataAttribute`?

**Comment by aivascu** [comment]
@R0boC0p at the time when this thread was created the test arguments were excluded from the output to prevent displaying data that was inconsistent with he actual test run.

I believe that since then the way pre-discovery works in Visual Studio has changed and the workaround is no longer necessary as the data in the test explorer is consistent with the data in the actual test.

Additionally the xUnit 2 AutoFixture attributes are currently being re-designed and the custom "data discoverer" will be disabled in the next v5 preview version.
