### ISSUE TITLE
System.ComponentModel.TypeConverter 4.0.1 was not found

### ISSUE THREAD

**Issue by joelleortiz** [AutoFixture/AutoFixture#1052]
Currently, when using AutoFixture.AutoNSubstitute in .NetCore projects, the following warning is shown when building the project:

> warning NU1603: Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found.

The issue has already been fixed in NSubstitute (https://github.com/nsubstitute/NSubstitute/issues/310) so I suppose an upgrade will fix this warning.

**Comment by zvirja** [comment]
Thanks for raising the issue!

Unfortunately, it's very unlikely we could apply this change in the nearby future 😟 This is a breaking change for our clients and we are not allowed to apply those ones in the minor updates as we follow the [SemVer](https://semver.org/). Also usually we are trying to target the lowest possible version for the greater compatibility and do not raise the lower boundary without having a strong reason for that.

I do understand that this issue is quite annoying. To work around it I could offer you the following options:
- suppress the warning manually like it's done [here](https://github.com/AutoFixture/AutoFixture/blob/d3e14a818b933d948ea82464b197a5aeb152f070/Src/AutoNSubstituteUnitTest/AutoNSubstituteUnitTest.csproj#L14).
- explicitly add a reference to a newer version of NSubstitute like [here](https://github.com/AutoFixture/AutoFixture/blob/d3e14a818b933d948ea82464b197a5aeb152f070/Src/AutoNSubstitute.NSubstitute3UnitTest/AutoNSubstitute.NSubstitute3UnitTest.csproj#L14).

Hope that helps! Sorry for the inconvenience 😟

**Comment by joelleortiz** [comment]
I added an explicit reference to NSubstitute as a workaround. Thanks for your help!

**Comment by zvirja** [comment]
@joelleortiz Thanks for the feedback!

I'm willing to close this issue as I don't consider this compiler warning as a strong enough reason to upgrade the min required version. We might still update the requirement in future if we have another reasons (e.g. we start to use newer API). Are you fine with that?

**Comment by joelleortiz** [comment]
No problem, closing this issue now. 

Thanks for your help!
