### ISSUE TITLE
String properties behave differently in a request

### ISSUE THREAD

**Issue by janissimsons** [AutoFixture/AutoFixture#1069]
While making my own SpecimenBuilder, I stumbled upon an issue, I don't know how to fix - basically string properties cannot be cast to PropertyInfo, so I cannot access CustomAttributes and the class they are declared in.
 
Here is some code I made for this example: 
```c#
    [Table("ItemTable", Schema = "prd")]
    public class Item : IEntity
    {
        [Column(@"Id", Order = 1, TypeName = "bigint")]
        [Display(Name = "Item id")]
        public int Id { get; set; }

        [Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Item name")]
        public string Name { get; set; }

        [Column(@"Effect", Order = 3, TypeName = "nvarchar")]
        [MaxLength(6)]
        [StringLength(6)]
        [Display(Name = "Item effect")]
        public string Effect { get; set; }

        [Column(@"LastUpdated", Order = 4, TypeName = "datetime")]
        [Display(Name = "Last Updated")]
        public System.DateTime? LastUpdated { get; set; }
    }
```
The first thing I do in my CustomSpecimen, is cast request to PropertyInfo, that works wonderful for all members of this class, except for strings.
```c#
        public object Create(object request, ISpecimenContext context)
        {
            var property = request as PropertyInfo;
            if (property == null) return new NoSpecimen();

            ColumnAttribute column = property.GetCustomAttribute<ColumnAttribute>();
            TableAttribute table = property.ReflectedType.GetCustomAttribute<TableAttribute>();
            
            ...
        }
```
The above code casts the Id and LastUpdated to properties and retrieves their custom attributes without any issues, however, when it comes to Name and Effect properties, the only request that ever comes in, is either of type string (TypeInfo not PropertyInfo), or it is a Ranged string request.  

Then, I thought I will be clever, and I will only take the class itself in the request and resolve the properties in a single call to my CustomSpecimen, like this:  
```c#
        public object Create(object request, ISpecimenContext context)
        {
            var typeInfo = request as TypeInfo;
            if (typeInfo == null) return new NoSpecimen();
            if (!typeInfo.ImplementedInterfaces.Contains(typeof(IEntity))) return new NoSpecimen();

            // Stores the class name, local offsets and other things for incrementing unique IDs
            PrepareForNextDataSet(typeInfo.FullName);
            TableAttribute table = typeInfo.GetCustomAttribute<TableAttribute>();

            var instance = Activator.CreateInstance(typeInfo.AsType());
            foreach (var prop in typeInfo.DeclaredProperties)
            {
                ColumnAttribute column = prop.GetCustomAttribute<ColumnAttribute>();
                // Tries to get info about this column from metadata
                UniqueKeyModel uniqueKeyModel = GetUniqueKeyModel(table.Name, column.Name);

                object resolved;
                // If this column is part of unique keys, then assign a unique id
                if (uniqueKeyModel?.UniqueKeyOrder != null)
                {
                    // try assigning unique id, if not possible then resolve from context
                    resolved = GetValueForProperty(prop) ?? context.Resolve(prop);
                }
                else
                {
                    // if field is not part of UniqueKeys - then randomize output
                    resolved = context.Resolve(prop);
                }
                prop.SetValue(instance, resolved, null);

            }

            return instance;
        }
```
Now, this approach works perfectly until I start to customize specific values using ICustomization interface or simple calls to Fixture.Build(), like this:  
```c#
    public class ItemCustomization : ICustomization
    {
        /// <inheritdoc />
        public void Customize(IFixture fixture)
        {
            fixture.Customize<Item>(c =>
                c.With(p => p.Name, "example"));
        }
    }  
```
And final usage:  
```c#
    Fixture fixture = new Fixture();
    fixture.Customizations.Add(new CustomSpecimen());
    fixture.Customize(new ItemCustomization());
    var result = fixture.CreateMany<Item>(5).ToList();
```

My specimen is no longer working, because customization has overriden specific values and the Item class does not get sent to my CustomSpecimen, only the remaining fields as primitive data types.

Please suggest a better way of doing this - in essence, what I am trying to accomplish is to have a CustomSpecimen that would populate fields for all types of entity framework generated classes. (I cannot use the default builders, because I have custom logic based on attributes).  
CustomSpecimen validates Column name and Table name attributes for each property against a list, and if that list contains an entry for this column & table, then it will assign a unique id. Otherwise, it will resolve the property from context.  
Then it should check, if any of the fields have been overriden with customization, if yes, then it should use that specific value instead.

**Comment by janissimsons** [comment]
@zvirja I would very much appreciate your input on this. Thank you.

**Comment by janissimsons** [comment]
Anyone, please? @moodmosaic @ecampidoglio @adamchester @zvirja @gertjvr

**Comment by moodmosaic** [comment]
@janissimsons, I'm not sure I completely follow the question here, but wouldn't something like [this](https://github.com/AutoFixture/AutoFixture/blob/d3e14a818b933d948ea82464b197a5aeb152f070/Src/AutoFixture/DataAnnotations/TimeSpanRangedRequestRelay.cs#L18-L24) work?

```
# Pseudocode

var candidate = request as RangedRequest;

if (candidate == null)
    return new NoSpecimen();

if (candidate.MemberType != typeof(String))
    return new NoSpecimen();

# Do something with `candidate`
# ...
```

**Comment by zvirja** [comment]
@janissimsons Good night! :) I need to stop apologize for the belated replays and put a disclaimer somewhere 😖 

I believe that I do understand your issue more or less  (👍 for the detailed description), so will try to help.

You put your custom builder to the `fixture.Customizations` collection, but it matters whether you add it to the end, or at the beginning. If [you look](https://github.com/AutoFixture/AutoFixture/blob/5ed2f8b8fb8061fddbed85b5209a26c2ceb3a317/Src/AutoFixture/Fixture.cs#L122) at the default `Customizations` builders (yes, this collection is not empty by default which I always find non-intuitive), you might notice that the last node is related to the data annotation attributes handle. It kicks in _before_ your builder and intercepts the `Name` and `Effect` properties, as they contain `MaxLength` and `StringLength` attribute. So your builder never receives the original `PropertyInfo` request, but instead the `RangedRequest` or `ConstrainedStringRequest` (depending in which order the relays are specified in our code).

To mitigate that, you have a few good approaches:
- Put your custom builder to the beginning of the `Customizations` collection using `fixture.Customizations.Insert(0, new CustomBuilder())`.
- Remove the built-in support for the data annotations using `fixture.Customize(new NoDataAnnotationsCustomization())`. The data annotations builder will be removed from customization, so properties will be never intercepted. I wouldn't recommend this way, as it's always better to respect data annotation attributes if those are present 😊 
- Build your code around the `RangedRequest` or `ConstrainedStringRequest` as advised above by @moodmosaic. Not sure it will work for you, as you likely need access to other member attributes, which are no longer available 😕 

If your specimen builder will work with individual `PropertyInfo` requests rather than with the whole type, then it should work fine if later you use `fixture.Customize(c => .....)` or `fixture.Build(...).Create()`. The `Customize<T>()` or `Build<T>()` methods inject customization at the very beginning of the chain of builders, so they will always precede your custom builder and intercept the `typeof(T)` requests. I wouldn't suggest you to fight with `typeof(T)` interception and better customize individual members, as you really cannot control too much here, especially with the `Build()`.

Hope my answer helps you 😉 If not - clarify what exactly doesn't work.

**Comment by janissimsons** [comment]
@zvirja Thank you! That explains why those properties where intercepted. I will use the first solution.

I think you should update the documentation, because from what I understood from wiki and the Pluralsight course is that whenever we add a custom ISpecimenBuilder to the Customizations list then it becomes the very first to handle all requests, and if that fails then the default builders kick in. 

@moodmosaic I cannot work with the RangedRequest, because as @zvirja said I need to access the other attributes that are defined for this property.  

#### One last question - since you know the AutoFixture internals much better than I do, is there a better approach to my general problem:

I have over 100 classes for which I need to generate valid data. Now, the SpecimenBuilder I have written generates data correctly for about 80% properties across all classes. However, there will always be some specific logic that applies only for a couple of fields that cannot be generalized.  

Right now, I have chosen to let the builder create data for each class, then override the fields in a loop and set them to specific values.
### An example:
```C#
private Class1 GetClass1(){
	var datasets = fixture.CreateMany<Class1>(DataSize).ToList()

	foreach(var set in datasets){
		set.Field25 += "Customer"; 
		set.Field27 = 5;
	}
	return datasets;
}

private Class2 GetClass2(){
	IList<string> BusinessArea = new List<string>()
    {
        "Private", "Industrial", "Commercial"
    };

	var datasets = fixture.CreateMany<Class2>(DataSize).ToList()

	foreach(var set in datasets){
		set.Field5 += BusinessArea[randomizer.Next(0, BusinessArea.Count - 1)];
		set.Field7 = "SPKey000";
		set.Field15 = utils.GetSynchronizedDateTime();
	}
	return datasets;
}

private Class3 GetClass3(){
	var datasets = fixture.CreateMany<Class3>(DataSize).ToList()

	foreach(var set in datasets){
		set.Field1 = 2;
		set.Field4 += "areaNum";
	}
	return datasets;
}
```
ICustomization override would only allow me to insert specific value for the whole data set, but in some cases I need to specify different values per each set.
 
As you can see, I will have to write at least 100 of these methods to set the correct data.
Is there any better approach that comes to your mind?

Thank you!

**Comment by zvirja** [comment]
Well, if you need to customize particular properties of particular types, it's unlikely you can avoid coding that explicitly. You might create some helper methods to do that in laconic way:

```c#
fixture.CustomizeMember<DtoType>(x => x.Property, (string str) => str + "_original")
```

but still you'll need to write those lines - one per each field/property.

--------

If you want to customize the individual properties for a batch, you might use the `Build()` syntax. It works perfectly fine for those cases:
```c#
            var fixture = new Fixture();

            var itemsWith42 = fixture
                .Build<Item>()
                .With(x => x.Number, 42)
                .CreateMany(10)
                .ToArray();

            var itemsWithSuperValues = fixture
                .Build<Item>()
                .Without(x => x.String)
                .Do(result => result.String = fixture.Create<string>() + "_SUPER")
                .CreateMany(10)
                .ToArray();
            
            
            Assert.All(itemsWith42, i => Assert.Equal(i.Number, 42));
            Assert.All(itemsWithSuperValues, i => Assert.EndsWith("SUPER", i.String));
```
Notice that clumsy `Without(x => x.Prop).Do(x => x.Prop = value)` pattern. That's because `Do()` callback is executed _before_ auto-properties assignment. After we implement #708 it will become possible to write smth like `.With(x => x.Value, (string str) => str + "_SUPER")`.

Additionally, the approach above should work perfectly fine if you already have member-level customizations, as they will be still applied for the rest members.

Does it work for you?

**Comment by janissimsons** [comment]
Yes, it does, thank you.

**Comment by zvirja** [comment]
@janissimsons Great, you are welcome :wink: Sorry again for the long response time - hope it was still in time.
