### ISSUE TITLE
Can't inject a Interface into a Func return value while using AutoFakeitEasy

### ISSUE THREAD

**Issue by IngoVals** [AutoFixture/AutoFixture#1085]
I'm not able to get AutoFixture to return a concrete class from a Func.

I'm not sure where the problem is, if it is with AutoFixture, AutoFakeItEasy or, and most likely, with myself.

So I have a *system under test* that takes a `Func` as a parameter. I need a good handle on this funcs return value, which is a Interface. With my config the return value would be faked with FakeItEasy, but in this case I want a concrete instance.

```
            [Theory, MyAutoData]
            public void MyTest(IFixture fixture, MySut sut)
            {
                fixture.Inject<IMyInterface>(GetMyConcreteInstance());

                var actual = sut.DoYourThing();

                Assert.Equal(0, actual);
            }
```

In my sut I might have.

```
            public MySut(Func<int, IMyInterface> myInterfaceFactory)
            
            public int DoYourThing()
            {
                var instance = this.myInterfaceFactory(42);
                
                return instance.MagicHappensHere();
            }
```

So normally the Func is an anonymous type from Autofixture, but it returns a Fake since it is a Interface.

I was hoping that the fixture inject would change that and the Func would return the concrete instance. Does FakeItEasy still have preference because of Customization order or is there something else I'm missing or just asssuming a functionality that is not present.

-----

Using the following packages

```
  <package id="AutoFixture" version="4.5.1" targetFramework="net471" />
  <package id="AutoFixture.AutoFakeItEasy" version="4.5.1" targetFramework="net471" />
  <package id="AutoFixture.Xunit2" version="4.5.1" targetFramework="net471" />
  <package id="FakeItEasy" version="4.9.1" targetFramework="net471" />```

**Comment by zvirja** [comment]
@IngoVals Hello,

You haven't provided me with [MVCE](https://stackoverflow.com/help/mcve), so I tried to guess what exact code you have.

The sample below works correctly:
```c#
    public class UnitTest1
    {
        [Theory, AutoFakeData]
        public void TestFunctionResult(IFixture fixture, MySut sut)
        {
            fixture.Inject<IMyInterface>(new MeaningOfLifeAndEtc());
            
            var result = sut.GetInterfaceNumber();
            
            Assert.Equal(42, result);
        }
    }

    public interface IMyInterface
    {
        int GetNumber();
    }

    public class MeaningOfLifeAndEtc : IMyInterface
    {
        public int GetNumber() => 42;
    }

    public class MySut
    {
        private readonly Func<int, IMyInterface> _interfaceSource;

        public MySut(Func<int, IMyInterface> interfaceSource)
        {
            _interfaceSource = interfaceSource;
        }

        public int GetInterfaceNumber() => _interfaceSource(100500).GetNumber();
    }

    public class AutoFakeData : AutoDataAttribute
    {
        public AutoFakeData()
            : base(() =>
            {
                var fixture = new Fixture();
                fixture.Customize(new AutoFakeItEasyCustomization
                {
                    ConfigureMembers = true,
                    GenerateDelegates = true
                });
                return fixture;
            })
        {
        }
    }
```

Notice a few things:
- If `GenerateDelegates` flag is not set, delegates are generated by the AutoFixture engine and those _are not_ Fakes. In that case the delegate result is resolved immediately [on delegate construction](https://github.com/AutoFixture/AutoFixture/blob/44db23d8d919f8c94faa30929550f660dcdbffd1/Src/AutoFixture/Kernel/DelegateGenerator.cs#L84).
- If `ConfigureMembers` is not set, the generated Fakes _will not_ use AutoFixture to resolve result. So if you set `GenerateDelegates`, but not set `ConfigureMembers`, you will get default AutoFakeItEasy's result for the delegates (I'm not using that library so don't know what exactly will be returned).

The sample I provided above works because:
- `GenerateDelegates` is set to `true`, so Fakes are generated for the delegates. Delegate result is resolved lazily in that case (on invocation).
- We inject interface implementation _before_ actual delegate invocation
- The `ConfigureMembers` is set to `true`, so delegate Fake will ask AutoFixture for the result and the injected is returned.

The sample below will also work:
```c#
    public class UnitTest1
    {
        [Theory, AutoFakeData]
        public void TestFunctionResult([Frozen] IMyInterface myInterface, MySut sut)
        {
            A.CallTo(() => myInterface.GetNumber()).Returns(42);
            
            var result = sut.GetInterfaceNumber();
            
            Assert.Equal(42, result);
        }
    }

    public class AutoFakeData : AutoDataAttribute
    {
        public AutoFakeData()
            : base(() =>
            {
                var fixture = new Fixture();
                fixture.Customize(new AutoFakeItEasyCustomization());
                return fixture;
            })
        {
        }
    }
```

Even though both `ConfigureMembers` and `GenerateDelegates` are not set (set to default `false` value), we freeze `IMyInterface` instance _before_ constructing the delegate (via the `Frozen` attribute). So later when delegate is invoked, it takes the exact instance of interface implementation and will get the expected result.

-----
I tried to explain you the principle, so you have better clarity when writing the code. Hope it's not puzzle-headed too much, so you can track the idea 😅 

Let me know if you have further questions 😉

**Comment by IngoVals** [comment]
I see, there are configuration options to get the result I was assuming it could get. That is great.

My real world example was pretty complicated and I was trying to inject a concrete IoC container since resolve methods can't be faked in Autofac ( they are static extension methods ) but I later found out that there is a AutoFake ( A FakeItEasy extension to Autofac ) for that purpose so I didn't actually have to use the AutoFixture inject in that one off case.

I will have to keep on experimenting with these 3 tools for testing to find out how best to set up tests.

Thanks for the great support.
