### ISSUE TITLE
IFixture problem with new keyword modifier

### ISSUE THREAD

**Issue by brunomoreirafaro** [AutoFixture/AutoFixture#1096]
Hello,

Recently I've updated AutoFixture from 3.51.0 to 4.6.0
Some of my tests are now failing. It seems the problem is related with the new keyword modifier.
I have 3 interfaces:

```
public interface IHaveDisplayName
{
	string DisplayName { get; set; }
}

public interface IEntity : IHaveDisplayName
{
	new string DisplayName { get; set; }
}

public interface IFeature
{
	IEntity PrimaryEntity { get; }
}
```

If I execute the tests in the attatched solution, one of them fails,

```
[Theory]
[AutoDomainData]
public void Test02_WithIFixture(IFixture fixture)
{
	// Arrange
	var entity = fixture.Create<IEntity>();
	var feature = fixture.Create<IFeature>();
	feature.PrimaryEntity.Returns(entity);

	// Act
	var primaryEntity = feature.PrimaryEntity;

	// Assert
	Assert.Equal(entity, primaryEntity);
}
```

 but if I comment the IEntity.DisplayName then they all pass.

```
public interface IEntity : IHaveDisplayName
{
	//new string DisplayName { get; set; }
}
```
I found a workaround to get them pass while maintaining the IEntity interface unchanged.
Before setting the returns, I save the PrimaryEntity in a variable.
```
[Theory]
[AutoDomainData]
public void Test03_WithIFixture2(IFixture fixture)
{
	// Arrange
	var entity = fixture.Create<IEntity>();
	var feature = fixture.Create<IFeature>();
	var bugFix = feature.PrimaryEntity;
	feature.PrimaryEntity.Returns(entity);

	// Act
	var primaryEntity = feature.PrimaryEntity;

	// Assert
	Assert.Equal(entity, primaryEntity);
}
```
Can you help me out?

[ClassLibrary1.zip](https://github.com/AutoFixture/AutoFixture/files/2730564/ClassLibrary1.zip)

**Comment by zvirja** [comment]
Hi @brunomoreirafaro,

Take my apologizes for the belayed reply. You raised a great question 😉 

Actually, the issue happens as a combination of a few products:
- The fact NSubstitute uses `Castle.Proxies`
- The way `Castle.Proxies` works under the hood
- The auto-configured mode of AutoFixture + NSubstitute integration.

As you noticed, the issue happens because Castle starts to generate properties which implement interface explicitly. Such properties cannot be virtual, so AutoFixture fills them when `IEntity` objects are created. That affects the internal NSubstitute invocation tracker, as the last invoked method now is not the `PrimaryEntity` property, but the `DisplayName` setter. The reason why the workaround helps is the caching - the `IEntity` object is created only on the first `PrimaryEntity` property access.

The simplest way to work around this issue is to use the [`Configure()` extension method](http://nsubstitute.github.io/help/configure/) introduced in NSubstitute v4. If you don't want to install a pre-release version, just grab [the method implementation](https://github.com/nsubstitute/NSubstitute/blob/c930ab1e21479ec36f43b45722c019f9e6a2edba/src/NSubstitute/Extensions/ConfigurationExtensions.cs) to your test project - it's really tiny. When you invoke this extension, AutoFixture will no longer create a temp `IEntity` object on `PrimaryEntity` property access, so the NSubstitute's call tracker will correctly recognize which property you would like to configure.

Hope that helps 😉

**Comment by zvirja** [comment]
The NSubstitute v4 is already out, so you have `Configure()` method out of the box.

It's unlikely we can do something from our side to improve the situation, so I'm closing the issue. Please re-open the issue if further assistance is needed 😉
