### ISSUE TITLE
Versioning of AutoMoq, Moq, and .NET Standard

### ISSUE THREAD

**Issue by stakx** [AutoFixture/AutoFixture#1110]
AutoFixture.AutoMoq currently claims to support Moq versions >= 4.7.0 && < 5.0.0 under .NET Standard 1.5. The upcoming version 4.11.0 of Moq however will no longer support .NET Standard 1.0. (See https://github.com/moq/moq4/pull/784, https://github.com/moq/moq4/pull/785, plus the [changelog entry](https://github.com/moq/moq4/blob/master/CHANGELOG.md#changed).

I suppose it would be necessary to publish a new version of AutoFixture.AutoMoq with an updated version range ending at <= 4.10.1 for .NET Standard 1.5.

Some background info: The project at the moq/moq4 repository (i.e. present-day Moq) is forever doomed to keep the major version at 4 since the next iteration of Moq (i.e. the project at moq/moq) is supposedly going to be major version 5. So Moq 4 cannot follow semver (though I wish that were different).

**Comment by stakx** [comment]
Btw., while we're on the topic of Moq versions: If it were possible to raise the minimum version of Moq to 4.8.0 for all targets, it *might* be possible to massively simplify AutoMoq through the use of a custom `DefaultValueProvider` (see https://github.com/moq/moq4/pull/533, https://github.com/moq/moq4/pull/536) that derives its return values from an associated AutoFixture fixture/context. (It should no longer be necessary to set up every single method and property.) I haven't looked into this closely, but I'd be happy to run a few tests and perhaps send a PR along that line if successful.

**Comment by zvirja** [comment]
@stakx Hey! Good catch, many thanks for letting me know about that!
First I got scared that I'll be forced to release a new major version because of that, but luckily I had wrong perception 😌 

Yes, we should update range. If you are sure that version with this change is definitely named `4.11.0`, then we can do it even now.

> Btw., while we're on the topic of Moq versions: If it were possible to raise the minimum version of Moq to 4.8.0 for all targets, it might be possible to massively simplify AutoMoq through the use of a custom DefaultValueProvider

It would be awesome, if we implement "native" support. And if you can contribute it - it's even more cool! 

> use of a custom DefaultValueProvider

As far as I remember, when we wanted to follow the same approach for NSubstitute, the main issue was that AutoFixture fills `ref` and `out` parameters, while mocking library had different behavior and was reluctant to change it. Because of that we implemented other approach, where AutoFixture is not a blind value provider, but is aware of the whole call and have capability to fill ref/out args.

> If it were possible to raise the minimum version of Moq to 4.8.0 for all targets

Unfortunately, we cannot work on that now, as we are not allowed to modify the minimal supported version because of SemVer 😟 But I will be happy to do that when we release a new major version of AutoFixture. I'll ping you when that time comes 😊

**Comment by stakx** [comment]
> Yes, we should update range. If you are sure that version with this change is definitely named 4.11.0, then we can do it even now.

About 98.7% sure. There's already a pre-release 4.11.0-rc1, and unless there's a huge public outcry against the now-missing .NET Standard 1.x support, I'll release 4.11.0 proper in about two weeks' time.

**Comment by zvirja** [comment]
@stakx Just checked - RC is still there. Could you please ping me when you release 4.11.0 version? :blush:

**Comment by stakx** [comment]
@zvirja: Will do!

**Comment by stakx** [comment]
@zvirja, I've just published Moq 4.11.0 to NuGet.
