### ISSUE TITLE
AutoFixture.AutoNSubstitute: SubstituteAttribute does not respect greedy constructor setup

### ISSUE THREAD

**Issue by Ergamon** [AutoFixture/AutoFixture#1124]
I am using Xunit and NSubstitute with the GreedyEngineParts class for my fixtures, so my AutoNSubstituteDataAttribute looks like this:

```c#
 public class AutoNSubstituteDataAttribute : AutoDataAttribute
  {
    public AutoNSubstituteDataAttribute()
        : base(CreateFixture)
    {
    }

    private static IFixture CreateFixture()
    {
      var customization = new AutoNSubstituteCustomization();
      var engineParts = new GreedyEngineParts();
      var fixture = new Fixture(engineParts);
      fixture.Customize(customization);
      return fixture;
    }
  }
```

Sadly I have also some legacy code to test, so I sometimes have to use the SubstituteAttribute.

Let´s say I have a class like this:

```c#
  public class Worker
  {
    private readonly ILogger logger;

    public Worker()
    {
    }

    public Worker(ILogger logger)
    {
      this.logger = logger;
    }

    public virtual string GetConstructorMessage()
    {
      return logger == null ? "constructor0" : "constructor1";
    }
  }
```
A test written like this will call the greediest constructor:
`    [Theory]
    [AutoNSubstituteData]
    public void Test1(Worker worker)
    {
    }`

But a test written like this will not:
`    [Theory]
    [AutoNSubstituteData]
    public void Test2([Substitute] Worker worker)
    {
    }`

**Comment by zvirja** [comment]
Hi @Ergamon,

Sorry for the late reply. When somebody puts a complicated question without nice easy answer it's very tempting to postpone it 😖 

It's a limitation of our existing extensibility architecture. Firstly it worth noticing that substitute activation is controlled by the NSubstitute library rather than by AutoFixture kernel. In our code we just craft arguments and pass them to NSubstitute where the magic happens. Our NSubstitute customization uses [its own](https://github.com/AutoFixture/AutoFixture/blob/e4f62e81f70a3c4a992505cb70b3a10a5878c5be/Src/AutoNSubstitute/NSubstituteMethodQuery.cs#L12) constructor selector, so the customized Engine Parts are simply ignored.

I don't see a quick nice workaround for that. Also I don't foresee changes in the nearby future which might solve this. I would probably advice creating `WorkerFixture` type inherited from the `Worker` and exposing a single constructor only. Later you could use `WorkerFixture` instead of `Worker` when required.

If you see better a way - feel free to share them back.

Thanks!

**Comment by zvirja** [comment]
One more solution might be to rewrite the `AutoNSubstituteCustomization` and use your own `NSubstituteGreedyMethodQuery` query which will always pick up a constructor with largest amount of arguments.

**Comment by Ergamon** [comment]
Dont worry, I am using this library for free, so there is no real expectation from my side to get asap replies ;)

Of course as you write it, I feels logical that these combinations of libraries sometimes have a quite different behavior. Just from a user perspective it felt inconsistent.

As said I only need this for legacy code we inherited. In this old code basically every class has 2 constructors and it is not possible to get rid of these in the near future :(

The main reason I need tests to figure out how the old parts work to replace them over time.

The idea of using a local inherited test class with only one constructor seems indeed an easy workaround.
I will also look into your 2nd idea.

Thx for your help and feedback
