### ISSUE TITLE
What about support for .NET Standard 2.1 and .NET Core 3.0?

### ISSUE THREAD

**Issue by ericvb** [AutoFixture/AutoFixture#1149]
In the near? future we want to port our existing app in .net core 2.2 to .net core 3.0.
What about AutoFixture?

**Comment by Kralizek** [comment]
What's stopping you from using AutoFixture in a .NET Core 3.0 application or to a .NET Standard 2.1 library?

**Comment by ericvb** [comment]
That is just my question, I hope that nothing will stop me...
I don't see .NET Standard 2.1 in the .NET platforms compability table...

**Comment by Kralizek** [comment]
Not a maintainer, just a contributor.

AutoFixture works at 99% with the API offered by .NET Standard 1.5. The missing 1% is composed by classes like MailMessage that were added in 2.0.

The double targeting is mostly a nicety because .NET Standard 1.x libraries were coming with a huge set of dependencies. The restore/build process was changed in 2.0 and targeting directly helps a quicker build experience.

Targeting 2.1 would be needed if the maintainers wanted to add some built-in support for types that are only available there. I cannot say whether or not this will happen but my bets are on the "no" side, also because I don't see any type in 2.1 that really needs a default configuration, maybe IAsyncEnumerable being the only exception.

That being said, for what it can matter, I have used AF and its glue libraries in a 3.0 test suite in production already and I didn't have any issue.
