### ISSUE TITLE
.Without not working when not immediately chained

### ISSUE THREAD

**Issue by kmjones77** [AutoFixture/AutoFixture#1211]
I am using v4.14.0.

I am trying to conditionally add a property to a builder similar to the below:

    var builder = this.TestDataFixture.Build<SomeClass>()
        .With(x => x.Something, true);

    if (someBool)
    {
        builder.With(x => x.Other, 999);
    }
    else 
    {
         builder.Without(x => x.Other);
    }

    var created = builder.Create();

If someBool is set to false, the Other property still gets set to a random value

**Comment by aivascu** [comment]
@kmjones77 this is due to the fact that each method in the invocation chain is creating a new builder instance.
You can think of it being similar to how you build LINQ statements. You can interrupt your query builder at any time and then use that `IQueryable` instance to create any number of queries that derivate from the original query.

To achieve what you're aiming for, you should assign the original `builder` variable the reference coming out of the `.With()` or `.Without()` statements.

```cs
var builder = this.TestDataFixture.Build<SomeClass>()
    .With(x => x.Something, true);

if (someBool)
{
    builder = builder.With(x => x.Other, 999);
}
else 
{
     builder = builder.Without(x => x.Other);
}

var created = builder.Create();
```

**Comment by kmjones77** [comment]
ok thanks a lot!
