### ISSUE TITLE
Tests never complete running when using third party API object from third-party API and OmitOnRecursionBehavior turned on

### ISSUE THREAD

**Issue by sethreidnz** [AutoFixture/AutoFixture#1273]
Hi there, this is a great library. I'm trying to figure out what I'm doing wrong in my configuration to use AutoFixture and AutoMoq along with the xunit Thoery attribute to create my SUTs and my test objects. I have a repo here that you can check out and see my issue:

https://github.com/sethreidnz/AutoFixtureStripe

What seems to happen is that if I remove the lines that [replace the recursion behavior](https://github.com/sethreidnz/AutoFixtureStripe/blob/main/src/AutoFixtureStripe.Tests/AutoFixture.cs#L25), then I will get hte standard recursion error. If I include it however, then the test never finishes, nor fails, it just hangs forever like its stuck in an infinite loop. Is this expected? You can see in the github action it just keeps going.

![image](https://user-images.githubusercontent.com/4713713/119941314-8af9af80-bfe4-11eb-8993-0365871e2889.png)

Any help would be great.

**Comment by aivascu** [comment]
@sethreidnz I don't think that this is expected behavior. I have cloned the repro repository but I haven't yet figured out what is going on.
From the first look the culprit is the `Customer` class, that is sprinkled all around the models.

**Comment by sethreidnz** [comment]
> @sethreidnz I don't think that this is expected behavior. I have cloned the repro repository but I haven't yet figured out what is going on.
> From the first look the culprit is the `Customer` class, that is sprinkled all around the models, but it should have been picked up by the recursion guard.

Thanks man. Yes it's strange isn't it. I've tried a number of things and can't get it to work.

**Comment by sethreidnz** [comment]
@aivascu if you end up having more of a look but not any time to fix, I'd be happy to try to do a PR, might have a dig into it next weekend but any info you have would be great

**Comment by Ergamon** [comment]
I also spend some time looking into it. No clue how clever the recursion part of AutoFixture is.

I made more or less a reduced copy of the Customer class and one of the problems is the TaxId class, which has a Customer property.

So Customer tries to create a list of TaxIds and each one tries to create a Customer again. There is a reason why this property is marked with a JsonIgnore attribute otherwise the serializer would stumble accross this too.

I guess you have to tell AutoFixture to ignore these properties too.

**Comment by aivascu** [comment]
@sethreidnz after more investigation I can conclude that, as strange as it might sound, this is expected behavior. The repeating requests are omitted as expected but the object tree just keeps going. Simply put the object graph is just that large. The request depth usually sits around 80 (i.e. `Customer->Property->Address->Property->Whatever->...`).

A simple solution would be to just ignore all auto-properties and include just those necessary for the tested scenario.
```cs
fixture.Customize<Customer>(c => c
    .OmitAutoProperties()
    .With(x => x.Address));

var customer = fixture.Create<Customer>();
```
A more generic solution would be to introduce something like a request depth guard, that would instruct AutoFixture to ignore requests after a certain depth. I've sketched one for you to try but it's in no way a tested solution https://gist.github.com/aivascu/b3357f3875f97c80f35a3c23127d6d20. 

You could take this idea and maybe propose a PR with the full implementation.

**Comment by Ergamon** [comment]
As written I have not the slightest clue of Stripe.net, but as far as I reverse engnieered the code, I found that all these "problematic" properties are marked with a JsonIgnoreAttribute.

So you could write your own omitter like this:
```
  public class JsonIgnoreAttributeOmitter : ISpecimenBuilder
  {
    public object Create(object request, ISpecimenContext context)
    {
      var property = request as PropertyInfo;
      var attribute = property?.GetCustomAttribute<JsonIgnoreAttribute>();

      if (attribute == null)
      {
        return new NoSpecimen();
      }

      return new OmitSpecimen();
    }
  }
```

and then change your AutoMoqAttribute like this
```
  public class AutoMoqDataAttribute : AutoDataAttribute
  {
    public AutoMoqDataAttribute()
      : base(GetDefaultFixture)
    {
    }

    private static IFixture GetDefaultFixture()
    {
      var autoMoqCustomization = new AutoMoqCustomization();
      var fixture = new Fixture().Customize(autoMoqCustomization);
      fixture.Register<HttpResponseHeaders>(() => null);
      fixture.Customizations.Add(new JsonIgnoreAttributeOmitter());

      return fixture;
    }
  }
```
Probably feels a little bit hacky, but at least your example works flawless in my tests.

**Comment by sethreidnz** [comment]
@aivascu @Ergamon I love open source! thanks so much for looking into this. I understand now I think. Let me see if I understand correctly...

I thought that recursion guard was going to prevent recursion from more thant the number provided (the default 1 in my case). But it is only guarding against that on each object so then each object is getting 1 level of recursion so this just keeps going? I'm struggling to figure out a scenario where this behavior would actually prevent recursion so maybe I'm misunderstanding how it works. But the above solutions work. I don't NEED the recursion, I just want the top level values.

**Comment by aivascu** [comment]
@sethreidnz yes I think you got it right. The recursion guard keeps AutoFixture from resolving the same request multiple times at different depth levels. Consider the example below:
```cs
class A {
public string Foo {get; set;}
public B Bar {get; set;}
public C Baz {get; set;}
}

class B {
public int Ping {get; set;}
public A Pong {get; set;}
}

class C {
public double Lee {get; set;}
public B Loo {get ;set;}
}
```
Assuming you are creating an SUT of type `A`, by default at a control depth of 1, the recursion guard will detect that the request for the value of property `Pong` (`-> A -> Bar -> B -> Pong -> A`) is the same as the request for the SUT  (`-> A`)and will trigger the recursion guard handler, which depending on the strategy will either omit  the property or throw at this point.
On the other path of execution `A -> Baz -> C -> Loo -> B` the recursion guard will not trigger for the type `B` even though it already resolved an instance of type `B` for the `A -> Bar` property.
Hope this explains how the recursion guard works.

**Comment by alecglen** [comment]
Thank you for your gist @aivascu ! It is working as expected for me.

I did also come across the solution provided in https://github.com/AutoFixture/AutoFixture/issues/1032, which seems to be a cleaner implementation to my novice eyes. However, when I try to use it in my tests, I receive the error below for any models with nullable fields.

`AutoFixture.ObjectCreationExceptionWithPath: AutoFixture was unable to create an instance from System.Nullable`1[System.DateTime], most likely because it has no public constructor, is an abstract or non-public type.`

I've been comparing the implementations and troubleshooting the last couple hours, but I'm too new to AutoFixture and haven't been able to find the problem. Would you be able to give it a glance when you have time?

**Comment by aivascu** [comment]
Hi @alecglen.
I'll gladly have a look when I have a bit of spare time, if your request is still relevant.
Could you open a new thread and provide a snippet of code to help me reproduce the issue?
