### ISSUE TITLE
Support for creating mocks from concrete types when using NSubstitute and AutoData

### ISSUE THREAD

**Issue by giulianob** [AutoFixture/AutoFixture#132]
Currently, it's easy to create a mock from a concrete type with Moq since you can just use Mock<SomeType> in your test method parameters. When using NSubstitute, it's difficult to do this since it doesn't wrap the type like Moq. One idea I had was to give an attribute like [Mock] to tell AutoFixture how to create the object. I was going to do this myself but I needed to pair both [Mock] and [Freeze] and wasn't able to really follow how the whole specimen builder process works in the FreezeCustomization to make them play nicely together.

**Comment by olegsych** [comment]
While understand the point @dhilgarth made regarding consistency with other AutoFixture mocking extensions, I think that it's even more important for these extensions to be consistent with their respective frameworks. In this particular case, implementing a class like `SubstituteFor<T>` doesn't fit the current design of NSubstitute and possibly the philosophy behind it. Although an implicit conversion operator, as @dhilgarth suggested, would make the experience less jarring, it can have side effects in weakly-typed code and still require use of `mock.Object` syntax in tests. I don't know if that's the case, but I wouldn't be surprised if the idea was rejected by the NSubstitute team. 
 
I like the original suggestion @dhilgarth made regarding a special parameter attribute, which could look like this.
```C#
public void SomeTest([Substitute] ConcreteClass dependency)
{
}
```

As @ploeh mentioned, CLR explicitly leaves order of attributes undefined, so the `[Frozen]` attribute could customize the fixture before the `[Substitute]` does and you can't predict if a concrete type or a substitute will get created. However, I agree with @giulianob in that this shouldn't limit AutoFixture and the fact that it does smells like a design limitation in AutoFixture or an implementation problem with the `FrozenAttribute`.

Another potential scenario affected by this limitation is the testing of non-sealed classes. I have [a large hierarchy of classes](https://github.com/olegsych/T4Toolbox/tree/master/src/T4Toolbox.VisualStudio/TemplateAnalysis) I want to test with AutoFixture. The abstract `SyntaxNode` class appears as a SUT in some tests and as a dependency in others. I want to use the `AutoConfiguredNSubstituteCustomization` because it automatically configures the substitutes consistently with what AutoFixture does for concrete types by default. However, this customization works only for those tests where `SyntaxNode` appears as a dependency and forces you to overspecify tests where it serves as a SUT. In the extreme cases, the same class can appear as both the SUT and the dependency in the same test. Here is a test I'd like to write:

```C#
public class SyntaxNodeTest
{
    [Theory, AutoConfiguredNSubstituteConventions]
    public void EqualsReturnsTrueWhenChildNodesMatch(
        SyntaxNode child, 
        [Unconfigured] SyntaxNode parent1,
        [Unconfigured] SyntaxNode parent2)
    {
        parent1.ChildNodes().Returns(child);
        parent2.ChildNodes().Returns(child);
        Assert.True(parent1.Equals(parent2));
    }
}
```

I want the default AutoFixture configureation logic to apply to the `child` parameter because its a dependency, but leave the `parent1` and `parent2` instances unconfigured because they are part of the SUT and have other abstract properties compared by the `Equals` method which are not relevant to this test. NSubstitute philosophy aside, I like the `[Unconfigured]` attribute works better than the `SubstituteFor<T>` wrapping type because it can be composed with other attributes, such as `[Substitute, Unconfigured, DoNotCallBase]`, for a dependency that serves as a pure mock or a dependency in legacy code where properties have undesirable side-effects. 

Thoughts?

**Comment by ploeh** [comment]
It looks like you're using xUnit.net, so you can extend the [`[Customize]` attribute](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit.net2/CustomizeAttribute.cs) if you want to add your own custom attributes that customize the fixture.

That's not a feature of AutoFixture's NSubstitute integration, but of its xUnit.net integration.

Since the order of attributes is undefined, you'd be doing this at your own risk, but as long as you don't combine them with other attributes, you should be okay :smile:

**Comment by olegsych** [comment]
That's what I thought as well, but after reading this thread I realized that I don't have good enough understanding of the `AutoFixture` codebase to see the potential problems. Please bear with me for a moment as I try to walk through what the implementation might be like. 

The `[Substitute]` attribute can be implemented by deriving from the `CustomizationAttribute`. The `ICustomization` it returns can insert an `ISpecimenBuilder` that creates a substitute in the beginning of `IFixture.Customizations`, which I assume would allow it to run before the default `ISpecimenBuilder` that creates a concrete type. When combined with the `[Frozen]` attribute, this will produce unpredictable results because the `FreezingCustomization` and the hypothetical `SubstituteCustomization` will insert their respective specimen builders that, depending on the order, will produce either a singleton instance of the concrete type or a transient instance of the substitute. Is this correct so far? 

The `[Unconfigured]` attribute could also be implemented as a `CustomizationAttribute`. However, to avoid re-implementing the logic in the `AutoConfiguredNSubstituteCustomization`, it would need to somehow change the `NSubstituteVirtualMethodsCommand` and the `NSubstituteSealedPropertiesCommand` to skip the "unconfigured" specimen. I assume that re-implementing the default logic in the `[Unconfigured]` attribute is undesirable because other attributes, such as the hypothetical `[DoNotCallBase]` would also need to do the same, so this feels like a general problem. Is it possible to reliably change well-known specimen builders and commands created by another customization? 

Going back to the `[Substitute]` attribute, it feels the undefined ordering problem with the `[Frozen]` attribute could also be solved if the `FreezingCustomization` could find and "decorate" the actual specimen builder instead of injecting a new one. Do you agree?

Any other thoughts or pointers would be much appreciated. The `ISpecimenBuilderTransformation` looked promising. Would you recommend digging further in this direction?

**Comment by ploeh** [comment]
> the FreezingCustomization and the hypothetical SubstituteCustomization will insert their respective specimen builders that, depending on the order, will produce either a singleton instance of the concrete type or a transient instance of the substitute. Is this correct so far?

Yes, that is correct.

**Comment by olegsych** [comment]
Thanks Mark. I've done a bit of digging and think I understand the problem with freezing better. I've opened a separate issue on just that topic. This one seems to be jumping all over and continuing multiple threadshere is probably not very productive.
