### ISSUE TITLE
🐛 Disable Property with Record type is not working

### ISSUE THREAD

**Issue by Tantol** [AutoFixture/AutoFixture#1387]
### Describe the Bug
https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#disable-property - Is not working when using `Record` type.

### Scenario
```
public record Test(string name, int? age);

Fixture fixture = new();
var fakeTest = fixture.Build<Test>().Without(x => x.age).Create();
```

```
--- fakeTest output: ---
{
    name: "2296053a-9f5c-4717-a3e5-ad9c38bc682f",
    age: 12345,
}
```

### Expected Behavior
```
--- fakeTest output: ---
{
    name: "2296053a-9f5c-4717-a3e5-ad9c38bc682f",
    age: null,
}
```

**Comment by aivascu** [comment]
Hello @Tantol,

This behavior is not a bug and it doesn't really depend on the type being a `record`.

When AutoFixture will try to instantiate the class it will first have to fill in the constructor parameters to create the object and then will look at the settable properties and will provide them values as well.

When the record in your example is being compiled it generates a `class` that looks something like below.

```cs
public class Test
{
    public Test(string name, int? age)
    {
        this.name = name;
        this.age = age;
    }

    public string name { get; set; }
    public int? age { get; set; }
}
```

Since the type is not properly encapsulated both properties will be set twice. Once via the constructor and once via the property setter. The fact that you've omitted the property does not mean AutoFixture will omit the constructor parameter as well.

There is a NuGet package I've created a while ago that offers the same kind of syntax for constructor customization called [AutoFixture.Community.Extensions](https://github.com/aivascu/AutoFixture.Community.Extensions). Using this package you should be able to write a test like below.

```cs
[Fact]
public void Foo()
{
    var fixture = new Fixture();
    var sut = fixture.Build<RecordType>()
        .FromFactory(x => x.WithParameter("page", default(int?)))
        .Without(x => x.page)
        .Create();

    Assert.Null(sut.page);
}
```

This feature should be added in the next major release of AutoFixture base package, but at the moment is still in early development so you might encounter some issues. 

Alternatively you can invoke the constructor using the currently available factory expression.

```cs
var sut = fixture.Build<RecordType>()
    .FromFactory((string name) => new RecordType(name, null))
    .Without(x => x.page)
    .Create();
```

**Comment by Tantol** [comment]
There is one more "solution" that I see now after ur replay.

Do not use "short" syntax for `record` type because it will auto generate constructor and AutoFixture will not omit his parameters.

Just use this syntax instead (without ctor)t:
```c#
public record Test
{
    public string name { get; init; } = default!;
    public int? age { get; init; }
}
```
