### ISSUE TITLE
🐛 Generator<T> hangs when used to generate a sample from limited range

### ISSUE THREAD

**Issue by pogosama** [AutoFixture/AutoFixture#1398]
I'm trying to use the `Generator` class to generate an `int` value from a specified range. But it seems that if the range is limited and I ask the class to generate the value many times it will hang at some point.

### Code sample
```c#
var fixture = new Fixture();
var generator = new Generator<int>(fixture);
for (var i = 0; i < 1000; i++) {
  var sample = generator.First(x => x >= 0 && x <= 3); // This will hang at some point
}
```

### Expected Behavior
I would expect that the above code should generate a valid sample 1000 times, even if it repeats the outcome.

Is this a bug or intended way of working? Does it track the generated samples and not return it anymore?

**Comment by aivascu** [comment]
@pogosama the generator is working as intended and it is generating random values.
The problem in your example is you are setting a condition that is very unlikely to ever occur, since the numbers generated are in the range of hundreds and  you are expecting a value between 0 and 3.
The intended use of the `Generator<T>` was to create sequences of data from a builder that's already customized according to the requirements.
```cs
var generator = new Generator<int>(fixure);
var sequence1 = generator.Take(10).ToList();
var sequence2 = generator.Take(17).ToList();
```
If you want to constrain the `Generator` you should either customize the Fixture or implement your own generator/specimen builder.

```cs
class MyConstrainedNumberGenerator : IEnumerable<int>
{
    private readonly ISpecimenBuilder builder;
    private RangedNumberRequest request;

    public MyConstrainedNumberGenerator(int min, int max, ISpecimenBuilder builder)
    {
        this.builder = builder;
        this.request = new RangedNumberRequest(typeof(int), min, max);
    }

    public IEnumerator<int> GetEnumerator()
    {
        var context = new SpecimenContext(this.builder);
        while(true)
        {
            yield return (int)context.Resolve(request);
        }
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```
```cs
[Fact]
public void Foo()
{
    var fixture = new Fixture();
    var generator = new MyConstrainedNumberGenerator(0, 3, fixture);
    for (var i = 0; i < 1000; i++)
    {
        var sample = generator.First(x => x >= 0 && x <= 3); // This will hang at some point
    }
}
```

**Comment by pogosama** [comment]
ok, thanks for the explanation!
