### ISSUE TITLE
🚨 GDPR compliance issue

### ISSUE THREAD

**Issue by MisinformedDNA** [AutoFixture/AutoFixture#1399]
Hello,

### Describe the issue
Moq is sending email addresses to SponsorLink

### Related links
https://github.com/moq/moq/issues/1372

### Affected products

Moq v4.20+

### Tasks

- [X] Issue reported to issue owner (if it comes from a third party library)
- [ ] Attached links to GitHub Advisory Database or other authority

### Screenshots

Thanks!

**Comment by aivascu** [comment]
@MisinformedDNA thank you for raising this, but the issue is irrelevant for AutoFixture, the minimum version that is currently supported is 4.1 for .NET Framework and 4.7 for .NET Standard respectively. Additionally AutoFixture intentionally keeps dependencies in the lower versions to maintain compatibility. Users of AutoFixture are responsible for installing the latest versions of the integrated frameworks alongside the AutoFixture packages.
