### ISSUE TITLE
🐛 RandomNumericSequenceGenerator with limits, can create values outside of these limits in certain scenarios

### ISSUE THREAD

**Issue by 3sRykaert** [AutoFixture/AutoFixture#1436]
### Describe the Bug
When using the RandomNumericSequenceGenerator with limits, a value can be created outside of these limits.

### Scenario
Create a RandomNumericSequenceGenerator with a min and max limit which is bigger then short.MaxValue.
Then ask for a new random number of type short.

### Expected Behavior
The random generated value needs to be between the min and max limits that are supplied to the RandomNumericSequenceGenerator.

### Tasks

- [ ] Updated all AutoFixture and related libraries
- [ ] Confirmed in support forums if behavior is expected

### More Information
Test case for the scenario above:
```
public class RandomNumericSequenceGeneratorTestCustom
    {
        private const int MinLimit = 1;
        private const int MaxLimit = int.MaxValue; //something bigger then short.MaxValue
        private static IFixture Fixture { get; } = new Fixture()
            .Customize(new NumericSequenceCustomization());
        
        private class NumericSequenceCustomization : ICustomization
        {
            public void Customize(IFixture fixture)
            {
                fixture.Customizations.Add(new RandomNumericSequenceGenerator(MinLimit, MaxLimit));
            }
        }

        [Fact]
        public void Test()
        {
            for (var i = 0; i < 1000; i++)
            {
                var random = Fixture.Create<short>();
                if (random < MinLimit)
                    throw new Exception($"Generated random value {random} outside of limits (smaller then {nameof(MinLimit)}: {MinLimit}");
                if (random > MaxLimit) //can never happen
                    throw new Exception($"Generated random value {random} outside of limits (bigger then {nameof(MaxLimit)}: {MaxLimit}");
            }
        }
    }
```

The error happens in https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/RandomNumericSequenceGenerator.cs in `private object CreateRandom(Type request)`
When casting the object to (in this example) a short, the limits aren't checked anymore. And since the generated (long) value is bigger then short.MaxValue, a negative short is returned after the casting to short.

**Comment by aivascu** [comment]
@3sRykaert thank you for raising this, but I think this behavior is by design. Consider the following scenario:

```cs
var fixture = new Fixture();
fixture.Customizations.Insert(0, new RandomNumericSequenceGenerator(300, 400));

var bytes = fixture.CreateMany<byte>(10).ToArray();
```
All values are outside of the `byte` range of numbers. What would be the expected value of the elements in this sequence?

The parameters in the constructor are not the Mix and Max value, though they can be if you specify just those two.
They are limits, within which the generator should generate values. 
So the way it works is that the generator will return a sequence of random numbers between the first and second number in the list. Once it is done and there are no more numbers within the first two numbers it will generate all the numbers within the second and the third number, and so on. If there are no more limits it will loop over and will again generate numbers within the first and the second number.
The example below shows this behavior more explicitly:

```cs
var generator = new Generator<int>(
    new CompositeSpecimenBuilder(
        new SeedIgnoringRelay(),
        new RandomNumericSequenceGenerator(2, 10, 50)));

var first = generator.Take(9).ToArray(); // 9,6,8,5,2,3,4,7,10
var second = generator.Take(40).ToArray(); 
// 20,28,42,23,17,24,35,44,26,34,38,41,37,25,29,13,31,46,19,47,30,
// 27,43,12,21,18,49,16,50,45,48,22,14,32,15,33,11,36,40,39

Assert.All(first, i => Assert.InRange(i, 2, 10));
Assert.All(second, i => Assert.InRange(i, 10, 50));
```
