### ISSUE TITLE
Move all Create overloads taking a seed to another library

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#151]
In my experience, the overloads for `Create` and `Freeze` methods that take a seed as extra argument cause much confusion (see [this discussion](http://stackoverflow.com/q/18161127/126014) for just one example).

All extension methods that take a seed as argument should be moved out of AutoFixture and into a separate library. This removes them from the mainstream AutoFixture API, which, hopefully, should make AutoFixture easier to use.

For those users still needing this feature, the extension methods will exist in a separate library, available as a separate NuGet package.

We can monitor the download statistics for that NuGet package to see if anyone uses that feature at all, and then completely retire it if that's not the case.

Please note that this is a breaking change, so the move cannot be done until AutoFixture 4, and complete removal will have to wait until AutoFixture 5 (if ever).

Implementation:
- [x] Create a standalone package with seeded methods
- [x] Update documentation and add a remark about package
- [x] Update Readme with a link to NuGet package and compatibility table.

**Comment by zvirja** [comment]
@moodmosaic I'm a bit confused by the plan, so could you please clarify it? The idea is to move the `Create` method overloads with a seed to a standalone Nuget package like `AutoFixture.SeededCreation`. It's fine.

However, the point with obsoletion confuses me. If we move extension methods to a standalone lib, we will to completely remove overloads from the AutoFixture library, rather than obsolete them. Otherwise, if user installs a Nuget  package, it will have 2 methods with exactly same signature and it will be annoying.. :worried:

**Comment by zvirja** [comment]
moodmosaic Pinging in case you missed this thread😉

**Comment by moodmosaic** [comment]
IIRC, the idea was to create a new *AutoFixture.Something* library and move those overloads there, but keep the same namespace in that hypothetical library.

**Comment by zvirja** [comment]
@moodmosaic Thanks for the confirmation.

As for the package name, I could advice the following ones:
- `AutoFixture.SeededCreation`
- `AutoFixture.CreateFromSeed`
- `AutoFixture.Seed`
- `AutoFixture.SeedExtensions`

Do you like any name? The last name looks the best for me. If you don't like the suggested names - do you see a more appropriate one? :wink:

**Comment by moodmosaic** [comment]
AutoFixture.SeededCreation sounds great to me 👍 😃

**Comment by zvirja** [comment]
Done! Extracted methods to the `AutoFixture.SeedExtensions` package in v4.
