### ISSUE TITLE
GuardClauseAssertion does not work with async methods

### ISSUE THREAD

**Issue by RedwoodForest** [AutoFixture/AutoFixture#268]
GuardClauseAssertion does not detect guards on async method parameters because the exception doesn't thrown until the returned task is waited or awaited.

**Comment by mniak** [comment]
@ploeh Do you have some suggestion on how could we write that does not violate the fail fast principle?
Should we just never use the async keyword or is there a nicer way to do this?

**Comment by ploeh** [comment]
@mniak, perhaps you can split up the code into a part that does the fail-fast check, and the part that does the actual async work... It's been a while since I last looked into issues like this.

**Comment by mniak** [comment]
Yeah, seems like a good and simple alternative.
Thank you very much!

**Comment by dexc99** [comment]
> Yeah, seems like a good and simple alternative.
> Thank you very much!

@mniak, Just out of interest what was your solution ?
I'm interested to know how you managed to split up your function without ending up with two async methods, one doing the guard assertions and one doing the actual work, as they will both still need to be async won't they ?

**Comment by mniak** [comment]
> I'm interested to know how you managed to split up your function without ending up with two async methods, one doing the guard assertions and one doing the actual work, as they will both still need to be async won't they ?

@dexc99 You can return the bare `Task`.
```csharp
public Task DoSomething(string parameter)
{
    _ = parameter ?? throw new ArgumentNullException(nameof(parameter));
    async Task Do()
    {
    	await Task.Delay(1000);
    }
    return Do();
}
```

**Comment by dexc99** [comment]
Only just got around to looking at this again. @mniak your suggestion worked perfectly. Thanks.

**Comment by Kralizek** [comment]
Just got bit by this again.

Is it just me or the suggested workaround are unacceptable because they force us to change our source based on an design choice and/or implementation of a testing framework?

I'd say in 2021 a testing framework for .NET should support natively async methods.

**Comment by ploeh** [comment]
I was reminded of this thread today, and perhaps it's worth a revisit.

First, a proviso:

1. I've been detached from AutoFixture since 2017. I no longer speak with any kind of authority.
2. The behaviour currently implemented `GuardClauseAssertion` is as it is, and it would be a breaking change to change it. See #1106 for an alternative.

There's such a thing as to reason out a stance from first principles, and then there's practical reality. As the adage goes, [the map is not the territory](https://en.wikipedia.org/wiki/Map%E2%80%93territory_relation).

My original position was based on principled reasoning. My experience with `async` and `await` was limited back then.

Since then I've worked extensively with asynchronous C# code, as I assume most other people have. Such day-to-day work creates a mental model of how asynchronous C# works, and I admit that once such a model is formed, it becomes quite natural to expect `async` methods to only throw once awaited.

For the record: I was wrong.
