### ISSUE TITLE
Compatibility with xUnit.net v2

### ISSUE THREAD

**Issue by expertchoice** [AutoFixture/AutoFixture#335]
xUnit.net v2 has deprecated xunit.extensions and this appears to make AutoFixture incompatible with this new version.  Are there plans to upgrade Autofixture to work with v2?

**Comment by ploeh** [comment]
My current thinking on this is that we should release an *AutoFixture.Xunit2* package once xUnit.net v2 is stable. There's actually [already a pull request for that](https://github.com/AutoFixture/AutoFixture/pull/294) by @TeaDrivenDev.

Is xUnit.net v2 stable?

I honestly don't know. [AFAICT, it's been in development for *more than two years*](http://www.nuget.org/packages/xunit), and I haven't been able to find any statement about the stability of neither alpha nor beta version.

Since xUnit.net v2 looks to be so incredibly slow-moving, I haven't wanted to invest resources in integrating with something that may still be far away - particularly when I can't see whether or not it's a moving target.

**Comment by TeaDrivenDev** [comment]
xUnit 2 is not stable yet. There was a new beta released a few weeks back, and from what I understood, they intend that to be the last one, so it will quite probably be another few months until a "gold" release. It also doesn't appear to be really stable API wise; there have been many comments about significant changes between beta versions.

It is not possible support xUnit 1 and 2 from the same library, so the proposed *AutoFixture.Xunit2* would be the way to go (as immediately deprecating xUnit 1 support is obviously out of the question).

The aforementioned pull request is a port of the existing *AutoFixture.Xunit* with the minimum necessary changes to target xUnit 2; the purpose was mostly to have the bulk of the work done in time for the final xUnit 2 release, and to be able to discuss any arising question as early as possible. I last updated it for beta 4 released around July or August; I haven't taken the time yet to move it to the most recent beta.

**Comment by ploeh** [comment]
@TeaDrivenDev, thank you for that detailed explanation, which also seems to correspond with my own perception of the issue so far.

@expertchoice, does this answer your question?

**Comment by expertchoice** [comment]
Mark,

Yes it does.  Much appreciated.  Thanks

**Comment by tomap** [comment]
Hi,

XUnit v2 is out now :)
https://www.nuget.org/packages/xunit/
Do you plan to update AutoFixture ?

Thank you

Thomas P.

**Comment by moodmosaic** [comment]
You may track the progress [here](https://github.com/AutoFixture/AutoFixture/issues/335).

**Comment by tomap** [comment]
Thank you :)
