### ISSUE TITLE
Consider making support for Regular Expressions optional in v4

### ISSUE THREAD

**Issue by moodmosaic** [AutoFixture/AutoFixture#352]
[This](https://github.com/AutoFixture/AutoFixture/issues/267) issue and [this](http://stackoverflow.com/q/28706286/467754) question might be trying to tell us that support for Regular Expressions is a feature that behaves kind of erratically.

Since we accept *any* valid Regular Expression as a `string`, it's impossible to support arbitrary input, and it's also impossible to constrain the input that we allow (since the [domain](http://en.wikipedia.org/wiki/Domain_of_a_function) is that of a string).

Maybe we could turn optional the support for Regular Expressions, or even remove the related classes from the codebase (in v4) and instead guide users to either use [Fare](https://github.com/moodmosaic/Fare) or [Rex](http://research.microsoft.com/en-us/projects/rex/) (or both), as in [this](https://github.com/AutoFixture/AutoFixture/issues/267#issuecomment-37654550) example.

**Comment by ploeh** [comment]
I certainly don't hope that the feature behaves erratically!

However, since a regular expression can be any string, it's also clear that there's an infinite set of strings that can't be be matched.

Do we get many 'support questions' regarding this feature?

As far as I can tell, it occasionally happens that someone writes a regular expression and can't understand why AutoFixture can't handle it. However, from my perspective, it doesn't look like it's particularly common, but I may be mistaken.

If we remove the feature and instead guide users to use Fare or Rex, would they be better off? Does Fare or Rex handle expressions that AutoFixture can't figure out?

Another question is whether it would be helpful to remove the feature and still support the other data annotations. Would it be harder for users to understand that AutoFixture respects e.g. the `[Range]` attribute, but not the `[Regex]` attribute?

Still another question is how much of a burden this is for you (@moodmosaic) to maintain, because I'll flat out admit that I'm relying on you for that part of AutoFixture. If you want to pull it out for that reason, I'll be open to do that in AutoFixture 4.

**Comment by moodmosaic** [comment]
>I certainly don't hope that the feature behaves erratically!

Now that I'm thinking of it, I shouldn't have used the word *erratic*. – What I want to describe is that we can't support *all* Regular Expressions. That's the problem that [other similar algorithms](https://code.google.com/p/xeger/wiki/XegerLimitations) face, as well.

>Do we get many 'support questions' regarding this feature?

Actually, we don't, as far as I can tell.

>If we remove the feature and instead guide users to use Fare or Rex, would they be better off? Does Fare or Rex handle expressions that AutoFixture can't figure out?

AutoFixture uses the algorithms of Fare. As far as I can tell, there are some Regular Expressions that Fare handles but Rex can't and vice versa. – A *Composite* that uses both can be the best of both worlds.

>Would it be harder for users to understand that AutoFixture respects e.g. the `[Range]` attribute, but not the `[Regex]` attribute?

True, that *can* possibly cause a bit of confusion.

>Still another question is how much of a burden this is for you (@moodmosaic) to maintain

The maintenance overhead has been low; since end of 2011 that this feature was added, there were two Pull Requests, #1 and #78. So, there isn't (yet) much of a burden maintaining it.

-----

Would it made sense to keep an eye on this (e.g. by adding the *question* label)? If we get more support questions, it can probably be easier to make a decision.

**Comment by ploeh** [comment]
I've added the *question* label, but in its current state, this issue isn't particularly *actionable*, so I'd rather prefer to close it, unless you have more to add...(?)

**Comment by moodmosaic** [comment]
Sure, let's close this. Given all the above, there's nothing to be done, at least for the time being.
