### ISSUE TITLE
Consider a different approach to combining cusomizations in xUnit DataAttributes

### ISSUE THREAD

**Issue by alexfoxgill** [AutoFixture/AutoFixture#364]
I realise this is probably not going to be a priority or even a reality but thought I'd float the ideas and see what you thought :)

Combining customizations by inheriting from `CompositeDataAttribute` can be cumbersome. If I have six customizations that I might want to combine, that's 63 potential attributes to create!

What I've tended to do in my code is to define a `CustomizationAttribute`:

```CSharp
public abstract class CustomizationAttribute : Attribute
{
    public abstract ICustomization GetCustomization();
}
```

which is then picked up by an AutoData derivative: 

```CSharp
public class CustomAutoDataAttribute : AutoDataAttribute
{
    public override IEnumerable<object[]> GetData(MethodInfo methodUnderTest, Type[] parameterTypes)
    {
        var customizations = methodUnderTest
            .GetCustomAttributes<CustomizationAttribute>()
            .Select(c => c.GetCustomization());

        foreach (var customization in customizations)
            this.Fixture.Customize(customization);

        return base.GetData(methodUnderTest, parameterTypes);
    }
}
```

This makes combining customizations easy and transparent:

```CSharp
[Theory, CustomAutoData]
[Effort, NSubstitute, RepeatCount(1)]
public void MyTest(...)
{
...
}
```

The [CustomizeAttribute](https://github.com/AutoFixture/AutoFixture/blob/20b91b313daba05fd51714323ad0575e4f25d8c9/Src/AutoFixture.xUnit.net/CustomizeAttribute.cs) exists already but is restricted to parameters only.

**Comment by ploeh** [comment]
Why don't you combine the Customizations using a `CompositeCustomization`, and then create a single attribute from that Customization? That's what I always do.

The tests in [AtomEventStore](https://github.com/GreanTech/AtomEventStore) follows that approach: [AtomEventsCustomization](https://github.com/GreanTech/AtomEventStore/blob/master/AtomEventStore.UnitTests/AtomEventsCustomization.cs) defines the Customization, and [AutoAtomDataAttribute](https://github.com/GreanTech/AtomEventStore/blob/master/AtomEventStore.UnitTests/AutoAtomDataAttribute.cs) is just an Adapter over that.

In that way, the Customization is also available for use with AutoFixture's imperative API, if you should ever need that (which *occasionally* happens to me).

**Comment by alexfoxgill** [comment]
I guess it depends on your needs, this is just my personal experience speaking. It's not something that's particularly hard for a user to do themselves, but I have found it an easier approach.

In the example above, I have customizations for [Effort](https://effort.codeplex.com/), NSubstitute and changing RepeatCount. To use all the combinations of these three, I would need to create an additional

1. EffortNSubstituteCustomization
2. NSubstituteRepeatCountCustomization
3. EffortRepeatCountCustomization
4. EffortNSubstituteRepeatCountCustomization

all with matching Attributes - and this gets exponentially compounded by further customizations: four customizations require an additional 11 composites, five require an additional 26.

Perhaps I am thinking about customizations in the wrong way, but it's been very helpful for me to easily pick and choose which ones are applied on a per-test basis.

**Comment by ploeh** [comment]
It sounds like you're using AutoFixture Customizations almost like C# `using` directives, or other sorts of *import* statements, pulling in *only* the minimal set of Customizations required for a particular test case.

Would you say that's an accurate description of your motivation?

**Comment by alexfoxgill** [comment]
Yes that's correct. In fact some customizations directly conflict with each other and can't be combined.

**Comment by ploeh** [comment]
If you will allow me draw a parallel: there are lots of examples that people find AutoFixture helpful because it keeps down the maintenance cost of unit tests. The archetypical example is when you add a second dependency to a class you're already testing. Without AutoFixture and Auto-Mocking, you'd have to address all the compiler errors that occur when you add a second constructor argument. With AutoFixture, no compiler errors are generated in this scenario.

(If you don't know what I'm talking about, just scan this [recent blog post](https://ruhul.wordpress.com/2015/04/06/autofixture-make-your-tests-slim-and-maintainable), or the last module of [the new AutoFixture Pluralsight course](http://www.shareasale.com/r.cfm?u=1017843&b=611266&m=53701&afftrack=&urllink=www%2Epluralsight%2Ecom%2Fcourses%2Fautofixture%2Ddotnet%2Dunit%2Dtest%2Dget%2Dstarted).)

The point is that if you use AutoFixture in a *consistent* manner, you'll have a *single* place you can go to address that type of problem for an entire test suite.

That's what I do with AutoFixture Customizations too: usually, I only have a *single* Customization for an entire unit test library. This establishes a set of conventions for the System Under Test (SUT), and pulls in the direction of making the SUT API design more consistent.

Consider, for example, your proposed approach: if you only use the bare minimum of fine-grained Customizations, you may have many unit test that don't include Auto-Mocking. Now imagine that you've been writing lots of tests of a class that has only [Concrete](http://blog.ploeh.dk/2012/08/31/ConcreteDependencies) or [Primitive Dependencies](http://blog.ploeh.dk/2012/07/02/PrimitiveDependencies). All unit tests that target that class don't *need* Auto-Mocking (because it has no Abstract Dependencies). However, what happens if you later discover that you need to add an Abstract Dependency to that class? All the existing tests of that class will now start failing, until you manually revisit all of them to add your Auto-Mocking attribute.

That, at least, is my experience with such an approach. Am I missing anything?

**Comment by alexfoxgill** [comment]
I think this comes down to how you use AutoFixture. Since it was created as a tool for TDD, I can see how the single customization would encourage a more consistent domain model. Sadly for me, my domain model is nowhere near consistent! Good thing that AutoFixture is so extensible that it's easily reconfigured to support my scenario :)

**Comment by ploeh** [comment]
Fair enough. I think it's always interesting to hear how AutoFixture is used by other people.

Going back to your original suggestion, I'd be concerned about this:

```C#
var customizations = methodUnderTest
    .GetCustomAttributes<CustomizationAttribute>()
    .Select(c => c.GetCustomization());

foreach (var customization in customizations)
    this.Fixture.Customize(customization);
```

The order of attributes returned by `GetCustomAttributes` is *not* guaranteed, so you could be running into order-dependent issues across different development machines - I've seen this happen in the wild.

This could be a big issue, since [the order of AutoFixture Customizations matters](http://blog.ploeh.dk/2012/07/31/TheorderofAutoFixtureCustomizationsmatter).

**Comment by alexfoxgill** [comment]
Oh, I hadn't realised that! Thanks for the heads up. That's a bit of a shame, I'll have to be careful how I organise my customizations
