### ISSUE TITLE
Freeze all interfaces by default? (AutoRhinoMock)

### ISSUE THREAD

**Issue by vorou** [AutoFixture/AutoFixture#399]
Here's how we're using the stubs w/ AutoRhinoMock right now:

    var helper = fixture.Freeze<IHelper>();
    var sut = fixture.Create<ProblemSolver>();
    helper.Stub(x => x.Help()).Return("It's me!");
    sut.Solve();

It could be rewritten like this (`Create` is rather a `GetFrozenInstance` here):

    fixture.Freeze<IHelper>();
    var sut = fixture.Create<ProblemSolver>();
    fixture.Create<IHelper>().Stub(x => x.Help()).Return("It's me!");
    sut.Solve();

Can I get rid of that `Freeze` call somehow? Is there a way to tell fixture to freeze all interfaces by default?

----------

More details: our test class layout has `SetUp` method in which we freeze all sut's dependencies and save them to fields. Then we use these fields to stub stuff in tests. What I want is to get rid of that freeze lines and fields, and just call `Create()` when I need to stub in a test.

I.e., replace this code:

```
SuperService sut;
IHelper helper;

public void SetUp()
{
  helper = fixture.Freeze<IHelper>();
  sut = fixture.Create<SuperService>();
}

public void Test1()
{
  helper.Stub(x => x.Help()).Return("panda");
  // ...
}
```

with this one:
```
SuperService sut;

public void SetUp()
{
  sut = fixture.Create<SuperService>();
}

public void Test1()
{
  fixture.Create<IHelper>().Stub(x => x.Help()).Return("panda");
  // ...
}
```

**Comment by mrinaldi** [comment]
I am assuming that ``ProblemSolver`` somehow gets ``IHelper`` injected, right?

What I usually do in these cases is to expose the ``IHelper`` through a readonly property, something like this:

```c#
public class ProblemSolver
{
    private readonly IHelper helper;
    public IHelper Helper {
        get { return helper; }
    }

    public ProblemSolver(IHelper helper) {
        this.helper = helper;
    }
}
```

Then you can setup your stub like this:

```c#
SuperService sut;

public void SetUp()
{
  sut = fixture.Create<SuperService>();
}

public void Test1()
{
  sut.Helper.Stub(x => x.Help()).Return("panda");
  // ...
}
```

**Comment by ploeh** [comment]
Like @mrinaldi, I was going to suggest the [Structural Inspection](http://blog.ploeh.dk/2013/04/04/structural-inspection) approach, but he beat me to it :smile: 

At that point, you may begin to wonder why you need to have `sut` as a class field. Why not let `fixture` create it when you need it?

@vorou, does this address your question?

**Comment by vorou** [comment]
@mrinaldi yep, `IHelper` is injected into `ProblemSolver`. Thanks for the snippet, it looks like an interesting option. However, the problem is although you got rid of all that `Freeze` calls, you instead have to write properties exposing the injected instances. So, in terms of number of LOC these two solutions are equal.

@ploeh thanks for the post, it's thoughtful and useful, as always!
I need that `sut` field since I'm sure I'll need it in each and every test. So, it's a matter of writing less LOC, I think.
It's an viable option, but although I liked it more than what we have now, it's not ideal. It looks like freezing all the interfaces by default would be a better one, is it possible?

**Comment by ploeh** [comment]
The short answer is that there's no such feature in AutoFixture.AutoRhinoMocks (or, IIRC, any of the other [Auto-Mocking](http://blog.ploeh.dk/2013/03/11/auto-mocking-container) Glue Libraries for AutoFixture).

It would most likely be possible to develop such a feature, but it would have to be a new `ICustomization` in AutoFixture.AutoRhinoMocks, because it would be a breaking change to change the existing `AutoRhinoMockCustomization` to behave in such a way.

That said...

> However, the problem is although you got rid of all that Freeze calls, you instead have to write properties exposing the injected instances. So, in terms of number of LOC these two solutions are equal.

Perhaps the line count would be similar, but you'd be moving that feature from your tests to the System Under Test (SUT). The most important benefit of TDD is to get feedback about the API of the SUT.

If, along the way, you learn that it would make the tests easier to write and maintain if you added Inspection Properties, you've learned something about the use of the SUT.

You can attempt to resist it, but I long since gave that up and just went with the flow. As long as it doesn't mess with the invariants of the SUT, I *act* on the feedback I get from my tests. If tests tell me that it would make my tests easier if I design the SUT's API in a certain way, it's a pretty good indication that it would make the SUT easier to use overall. After all, the [unit tests are the *first* client of the production API](http://blog.ploeh.dk/2011/11/10/TDDimprovesreusability).

**Comment by vorou** [comment]
@ploeh thanks both for the short and the long answers.

PS: Re-read your post, it's funny to watch how as I gain more experience in the field, some ideas are moving for me from "Have no idea what is he talking about" to "That was exactly what I was thinking!".
