### ISSUE TITLE
AutoFixture.Idoms: GuardClauseAssertion for asyc/await methods

### ISSUE THREAD

**Issue by jwChung** [AutoFixture/AutoFixture#401]
I was wondering that the issue(#268) can be re-considered if we can tell whether a method is async/await or not.

[This thread from SO](http://stackoverflow.com/questions/20350397/how-can-i-tell-if-a-c-sharp-method-is-async-await-via-reflection) shows a simple way for spotting async/await method.

**Comment by moodmosaic** [comment]
That could be interesting. :smiley:

What's the advantage of using that in #268, instead of checking whether the return value is a `Task`?

**Comment by jwChung** [comment]
With only checking whether a return type is `Task`, we cannot assert a certain method is async/await. In https://github.com/AutoFixture/AutoFixture/issues/268#issuecomment-37755864, @ploeh shows the two type of methods - the one(`Foo` method) should not be waited but the other(`Bar` method) should be waited as the `Bar` method violates the Fail Fast principle - but the both have the `Task` return type.

**Comment by ploeh** [comment]
@jwChung What do you propose to change?

**Comment by jwChung** [comment]
In the samples you showed at https://github.com/AutoFixture/AutoFixture/issues/268#issuecomment-37755864, the only `Foo` method is passed by `GuardClauseAssertion`, but the other `Bar` method isn't, as the Bar method violates he Fail Fast principle.

In this point, I was thinking how to make the `Bar` method passed. Can we address this issue if being able to determine whether method is async/await or not?

**Comment by ploeh** [comment]
Why should the `Bar` method pass? Its observable behaviour is incorrect.

**Comment by jwChung** [comment]
If so,  how can we test, using `GuardClauseAssertion`, that the `Bar` method has correct guard clauses?
To test async/await methods, should we every time extract a method to make the method not adorned with the `async` keyword as below the `BarWith` method?

```
public Task<string> Bar(object obj)
{
    if (obj == null)
        throw new ArgumentNullException("obj");

    return BarWith(obj);
}

private async Task<string> BarWith(object obj)
{
    return await Task.Factory.StartNew(() => obj.ToString());
}
```

**Comment by ploeh** [comment]
`GuardClauseAssertion` is concerned with the *observable* behaviour of members. If you want a member to behave correctly (i.e. fail fast), then that will be necessary - or just don't use the `async` and `await` keywords at all.

**Comment by jwChung** [comment]
I may need to understand the `GuardClauseAssertion` behaviour deeply. Thank for your explanation.

**Comment by ploeh** [comment]
FWIW, I don't think you need to understand `GuardClauseAssertion`. The overall point is that [the `Bar` method doesn't have the desired observable behaviour](https://github.com/AutoFixture/AutoFixture/issues/268#issuecomment-37755864), because it doesn't fail fast.

You could say that it's unfortunate that the `async` and `await` keywords are implemented like this by the C# compiler, because it makes them much less useful, but at least this behaviour is consistent with how `yield` behaves.

Still, from the viewpoint of an external user of a reusable library, it doesn't matter which keywords were used to write a particular feature. What matters to an external user is that the *observed behaviour* is appropriate.
