### ISSUE TITLE
SemanticComparison's CreateProxy doesn't work as advertised with Likeness<TSource,TDestination>

### ISSUE THREAD

**Issue by jrnail23** [AutoFixture/AutoFixture#406]
The below example is a failing test based on a scenario nearly identical to the one @ploeh presented in his resemblance and likeness blog post: http://blog.ploeh.dk/2012/06/22/ResemblanceandLikeness/

FYI, This test depends on XUnit and AutoNSubstitute.

```csharp
    public class ResemblanceTests
    {
        [Fact]
        public void EntityShouldBeAdded()
        {
            var fixture = new Fixture().Customize(new AutoNSubstituteCustomization());

            var mockRepository = fixture.Freeze<IRepository>();
            var dummyCommand = fixture.Create<Command>();

            var sut = fixture.Create<Handler>();

            sut.Handle(dummyCommand);

            var entityResemblance = dummyCommand.AsSource().OfLikeness<Entity>().CreateProxy();

            mockRepository.Received().Add(entityResemblance);
        }

        public class Command
        {
            public string Name { get; set; }
        }

        public class Entity
        {
            public string Name { get; set; }
        }

        public class Handler
        {
            private readonly IRepository _repository;

            public Handler(IRepository repository)
            {
                _repository = repository;
            }

            public void Handle(Command command)
            {
                var entity = new Entity {Name = command.Name};

                _repository.Add(entity);
            }
        }

        public interface IRepository
        {
            void Add(Entity entity);
        }
    }
```

As best I can tell from debugging the source, it looks like the issues @jamesfoster raised in #99 (https://github.com/AutoFixture/AutoFixture/issues/99#issuecomment-17417226) were never really addressed for resemblances created from `Likeness<TSource,TDestination>.CreateProxy()`.

When NSubstitute calls `Equals` on the resemblance (via `SemanticComparer<TSource, TDestination>`), the two types being compared are `EntityProxyBlahBlahBlah` and `Entity`.  

As you can see here https://github.com/AutoFixture/AutoFixture/blob/master/Src/SemanticComparison/SemanticComparer.cs#L58, they can never be equal according to the `SemanticComparer`'s `Equals` implementation, since neither type derives from `TSource` (`Command` in my example above), so `CreateProxy` simply doesn't work for creating resemblances from a source type to a destination type.

**Comment by moodmosaic** [comment]
Thank you for reporting this! – The described issue looks like a *similar* bug with the one at #99.

After a [long discussion](https://github.com/AutoFixture/AutoFixture/issues/99), [we came to a conclusion](https://github.com/AutoFixture/AutoFixture/issues/99#issuecomment-17776764) that [the Mapping part could be separated](https://github.com/AutoFixture/AutoFixture/issues/99#issuecomment-17901981), which means that `entityResemblance` should be created as:

```
using AutoMapper;
...
var entityResemblance =
    new Likeness<Entity>(
        Mapper.DynamicMap<Entity>(dummyCommand)).ToResemblance();
```

If you replace `entityResemblance` with the one shown above, the test passes.

---

Essentially, #99 proves that `CreateProxy` is too ambitious trying to do *2* things at once: Mapping and Comparison.

Long story (#99) short, I'd try to *avoid* `CreateProxy` nowadays — even though I introduced this feature.

**Comment by ploeh** [comment]
Should we deprecate the method, then?

**Comment by moodmosaic** [comment]
Yes, I think so. – If we do that, we should also provide examples of how to use `ToResemblance` instead...

**Comment by jrnail23** [comment]
Is it feasible to add `ToResemblance` to `Likeness<TSource,TDestination`, to satisfy the scenario I posted above, without having to resort to automapper (or other similar fx)?
The thing that made that scenario so appealing, as introduced in @ploeh's blog post, is that it was so elegant and concise.  
That said, it's clear that `CreateProxy` doesn't quite do what was intended, so I agree that deprecation is desirable.

**Comment by moodmosaic** [comment]
The `ToResemblance` method is already available. The code snippet that I've provided above, compiles.

**Comment by jrnail23** [comment]
@moodmosaic, `ToResemblance` only exists on `Likeness<T>`.  It does not exist on `Likeness<TSource,TDestination>`.
Those two types are actually entirely independent of each other, although one might tend to assume that `Likeness<T>` would be a subclass of `Likeness<TSource,TDestination>`, i.e.,
```csharp
public class Likeness<T> : Likeness<T,T>
...
```

**Comment by moodmosaic** [comment]
That's true; these two types are not related, and each one is customized in a different way.

* `Likeness<T1, T2>` is customized by a fluent interface.
* `Likeness<TClass>` is customized by supplying an `IEqualityComparer<TClass>`.

Adding `ToResemblance` *also* in `Likeness<T1, T2>` would solve the problem described in this issue with the minimum changes in the code. – Instead of `CreateProxy` you'd have to call `ToResemblance`.

On the other hand, I'm wondering if there will be again any edge cases, where it's not going to work, and then we'll end up deprecating *2* methods...

We should consider carefully before taking this direction as it might end up resulting to (an even higher) cognitive load... 

---

To use `ToResemblance` in your scenario, change this part:

```
dummyCommand.AsSource().OfLikeness<Entity>().CreateProxy();
```

with this:

```
var value = new Entity { Name = dummyCommand.Name };
new Likeness<Entity>(value).ToResemblance();
```

– or with this, if you wish to use AutoMapper:

```
new Likeness<Entity>(Mapper.DynamicMap<Entity>(dummyCommand)).ToResemblance();
```

---

Are all the above acceptable for your scenario? What other use cases you have?

**Comment by ploeh** [comment]
My current thinking of this is that `Likeness<TSource, TDestination>` is a dead end; I'm strongly considering deprecating the entire class.

When I originally created it, it never occurred to me to separate the concerns of mapping from the concerns of comparison, so it represents intermingled concerns.

As @moodmosaic points out, there's considerable cognitive load involved with this class, and everyone seems to have slightly conflicting expectations about how it should work. While we could attempt to 'fix' it, this indicates to me that the original design is flawed.

Much later it occurred to us to separate those concerns, which is why we then created `Likeness<T>`. It *only* does comparison, which means that you're free to first map your source object into an instance of the destination type - in whichever way you want.

You can use AutoMapper, custom mapping functions, inline maps, or whatever you prefer. This gives you an opportunity to pick exactly the tool or technique that suits you, instead of being forced into a subpar implementation that may behave differently from what you want.

---

BTW, nothing prevents you from creating a mini-DSL for your tests based on the examples @moodmosaic provides, so that you'd be able to write something like

```C#
var entityResemblance = dummyCommand.MapTo<Entity>().ToLikeness().CreateProxy();
```

using a couple of extension methods.

**Comment by ploeh** [comment]
As explained [above](#issuecomment-104753427), I don't think we should attempt to 'address' this issue.
