### ISSUE TITLE
Enable detailed tracing for Likeness.Equals method

### ISSUE THREAD

**Issue by sachevl** [AutoFixture/AutoFixture#431]
Most of the times it is hard to identify why likeness fails. One may use ShouldEqual method and catch LikenessException, but it is not straightforward when asserting collections. 

e.g.
`CollectionAssert.AreEquivalent(expected, actual);`

gives:
```
Expected: equivalent to < <Likeness of Class1>, <Likeness of Class1> > 
But was:  < <Class2>, <Class2> >
```

**Comment by ploeh** [comment]
It's true that it can be difficult to troubleshoot, but since collection comparisons rely on equality comparisons, the return value when two elements in a collection is compared, is already given: it's `bool`, so it doesn't provide an option to provide more information.

How would you suggest addressing this problem?

**Comment by sachevl** [comment]
Collection assertion seems to be a special case, because in order to test collection likeness it is enough to configure likeness of elements only.
Then collection themselves might be compared in 2 different modes
 1. Equals. Meaning that collections must have the same count, and contain equal objects in order
 2. Equivalent. Meaning that they contain the same objects regardless of order
   * Same size?
   * Different size, meaning that there might be duplicated objects?

There might be the following extension methods:
If we already have collection of likenesses:
```c#
public static void ShouldEqual<T1, T2>(this IEnumerable<Likeness<T1, T2>> likenessCollection, IEnumerable<T2> actualCollection) {...}

public static void ShouldEquivalent<T1, T2>(this IEnumerable<Likeness<T1, T2>> likenessCollection, IEnumerable<T2> actualCollection) {...}
```
If we have a collection and can configure likeness in place similar to this http://stackoverflow.com/questions/11718761/applying-autofixture-semanticcomparison-oflikeness-to-sequences-collections
```c#
public static void ShouldEqual<T1, T2>(this IEnumerable<T1> that, IEnumerable<T2> source, Func<Likeness<T2, T1>, IEquatable<T1>> customizeLikeness) {...}

public static void ShouldEquivalent<T1, T2>(this IEnumerable<T1> that, IEnumerable<T2> source, Func<Likeness<T2, T1>, IEquatable<T1>> customizeLikeness) {...}
```

Those method might throw some extended version of `LikenessException` e.g. `CollectionLikenessException`, where it would list the differences in details.

Furthermore we probably need to extend `Do` extension method to have overload for the collections if we want to test classes like this

```c#
public class Order
{
  public ICollection<Item> Items { get; }
}
...
var expectedOrder = receivedOrder.AsSource().OfLikeness<Order>()
    .With(o => o.Items).Do(items => items.ShouldEqual(receivedOrder.Items));
...
excpectedOrder.ShouldEqual(actualOrder);
```

**Comment by ploeh** [comment]
Thank you for providing some quite reasonable ideas for addressing this issue. I have to admit that I hadn't really thought along those lines :flushed: 

A couple of things to be aware of:

- [I consider `Likeness<TSource, TDestination>` a dead end](https://github.com/AutoFixture/AutoFixture/issues/408). It's not yet deprecated, but it might be. If Likeness has a future at all, I'm more inclined to bet on `Likeness<T>`.
- In the case of introducing a new exception class like `CollectionLikenessException`, it *shouldn't* derive from `LikenessException` unless there are compelling reasons to do so.
- Any contributor considering tackling this issue is encouraged to [split the work into several small pull requests](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests). It seems like one could do one pull request for `ShouldEqual`, another for `ShouldBeEquivalent`, and a third for any `Do` enhancement.

FWIW, I don't think this feature is at all easy to implement, which is the main reason that I'm not adding [the jump-in tag](http://nikcodes.com/2013/05/10/new-contributor-jump-in); I don't think it'd be a good feature to get started with AutoFixture as a new contributor. It doesn't mean that only core contributors can address it; everyone is still welcome.

To be open and honest about this: I have no intention looking into this myself, and I reserve the right to close this issue if it becomes inactive.

Along the years, I've come to the conclusion that every time I need to use `Likeness`, it's a design smell that my system under test should have better equality behaviour. When I write C# code, I aggressively give all my classes structural equality, which removes most of the need for `Likeness`.

Granted, sometimes you need to interact with objects you don't control (such as BCL objects), so `Likeness` still has its place. It's just not a high priority for me.

**Comment by ploeh** [comment]
Closing, due to lack of activity.
