### ISSUE TITLE
InlineAutoData no way to specify custom AutoDataAttribute

### ISSUE THREAD

**Issue by stevenao** [AutoFixture/AutoFixture#457]
Although the ctor has a AutoDataAttribute parameter, there is no way to use it in practice. It is confusing the real intention of it. If it is in fact not the intention to take in an AutoDataAttribute. It is better to make that ctor protected for the case that you can inherit from it.

**Comment by ploeh** [comment]
There *is* a way to use it in practice, although I admit that it can be difficult to find information about that. That constructor overload exists to enable you to create a derived class that customizes the behaviour of the attribute. You can see an [example in AtomEventStore](https://github.com/GreanTech/AtomEventStore/blob/master/AtomEventStore.UnitTests/InlineAutoAtomDataAttribute.cs), including [usage examples](https://github.com/GreanTech/AtomEventStore/blob/master/AtomEventStore.UnitTests/LifoEventsTests.cs#L144-L192).

Since this information is too difficult to find, we ought to add an example to the documentation.

**Comment by ploeh** [comment]
Added *enhancement* and *jump in* labels to indicate that we should enhance the documentation. When that's done, I think we can close this issue, unless @stevenao objects.

**Comment by stevenao** [comment]
I was confused at the first place when I was trying to use it as an attribute, but later I figured that I should make a class to inherit from it. I agree that a little more documentation will be nice. That can be just a little comment in the source code <summary> section. Thanks @ploeh!

**Comment by StefanoChiodino** [comment]
I've found the constructor used in the example given by @ploeh is obsolete and for whatever reason didn't work. I just extracted the `Func<IFixture>`  and used that instead of the and worked just fine.
