### ISSUE TITLE
Can't create Customization for Enums

### ISSUE THREAD

**Issue by SurajGupta** [AutoFixture/AutoFixture#484]
I can't seem to add a customization for Enums, whereas my customization of Bool seems to work just fine.  My Enum generator is never called with a `request` object of type `Enum`.  I'm not familiar with the internals of AutoFixture, but i'm wondering if its because `DefaultPrimitiveBuilders` doesn't include `EnumGenerator` as it does `BoolSwitch`.  `EnumGenerator` seems to be referenced in the constructor of `Fixture`.  What am I missing?  Should `EnumGenerator` be moved to `DefaultPrimitiveBuilders`?

**Comment by ploeh** [comment]
What have you tried?

**Comment by SurajGupta** [comment]
sorry should I have included repro...

I am calling this:

    var fixture = new Fixture();
    fixture.Customization.Add(new RandomEnumSequenceGenerator());
    fixture.Create<Number>();    

using these types:

    public enum Number
    {
        One,
        Two,
        Three
    }

    public class RandomEnumSequenceGenerator : ISpecimenBuilder
    {
        public object Create(object request, ISpecimenContext context)
        {
            // can I handle this request?
            var t = request as Type;
            if ((t == null) || !t.IsEnum)
            {
                return new NoSpecimen();
            }

            // get random enum value
            var enumValues = Enum.GetValues(t).Cast<object>().ToList();
            var randomIndex = ThreadSafeRandom.Next(0, enumValues.Count);
            var result = enumValues[randomIndex];
            return result;
        }
    }


However, the `Create` method is never called.

**Comment by ploeh** [comment]
When you `Add` anything to a collection, you add it *after* all other items. In general, you want a Customization to override all other behaviour, so it's good practice to `Insert` it at index `0`.

Usually it doesn't matter much, because `Customizations` is *mostly* empty. One of the few exceptions from that rule is indeed for `enums`, where the `SpecimenBuilder` lives there, instead of in the 'engine'. That's confusing; please accept my apologies for that.

(To be honest, I seem to recall that there's a *reason* for that design decision, but ATM I can't remember what it was. I'll need to investigate.)

**Comment by SurajGupta** [comment]
worked!  Thank you for the quick turnaround on this!
Its funny because the thought of ordering did occur to me, but `Add`ing `RandomNumericSequenceGenerator` seemed to work just fine, so I incorrectly assumed that the convention was that AutoFixture would use anything `Add`ed before falling back to default generators.

**Comment by ploeh** [comment]
I dug around a little in order to understand why `EnumGenerator` is contained in `Customizations`, instead of inside of the core engine parts of `Fixture`...

The only commit I've been able to find that even talks about this is 838eed8ba8210b8687a920806a7702ef751a8a61, but it doesn't really provide a satisfactory explanation. FWIW, the commit that introduced `EnumGenerator` is b01e612a4fba3a1a83aa7ad10e6c5734e1547769, but it gives no explanation for the placement.

While digging around, however, I was reminded that some Specimen Builders are placed in either `Customization` or `ResidueCollectors` in order to be *outside* of `AutoPropertiesTarget`. This may explain the placement of `EnumGenerator` as well. Contrary to what I'd expect, an enum is, it turns out, a *mutable* value!

The following FSI session demonstrates this:

```F#
> let mutable red = ConsoleColor.Red;;
val mutable red : ConsoleColor = Red
> red.value__;;
val it : int = 12
> red.value__ <- 9;;
val it : unit = ()
> red;;
val it : ConsoleColor = Blue
```

If `EnumGenerator` was placed in `DefaultEngineParts`, every generated enum value would pass through `AutoPropertiesCommand` and have its `value__` field mutated on its way out. Not only that, but `value__` would be assigned a random value, so could easily be assigned a value outside of the valid range of values for that enum:

```F#
> red.value__ <- 211;;
val it : unit = ()
> red;;
val it : ConsoleColor = 211
```

**Comment by SurajGupta** [comment]
thanks for digging into this!  this is great documentation in case this topic comes up again.  Sounds like we want to keep it as-is?

**Comment by ploeh** [comment]
It may be possible to move `EnumGenerator` to somewhere else entirely... I can't fully predict the implications of that, but I suppose we could try and see what happens :smile:

**Comment by zaytsevvla** [comment]
Why not add `RandomEnumSequenceCustomization` in way you add `RandomBooleanSequenceCustomization`?

**Comment by zvirja** [comment]
Closing this one as no actions are required here.

Later we might consider changing the core, so that predefined builders are not placed to the `Customizations` collection, but is the whole new story.
