### ISSUE TITLE
Update AutoFixture.NUnit2 to use NUnit 2.6.4

### ISSUE THREAD

**Issue by AlexanderButs** [AutoFixture/AutoFixture#488]
Hi, guys.

Is it possible to update AutoFixture.NUnit2 to use NUnit 2.6.4?

Everything works fine with NUnit 2.6.2 but only from command line. 
If I use the latest Resharper which uses NUnit 2.6.4 runner it doesn't work (also i can choose custom test runner for resharper but it doesn't work as well with NUnit 2.6.2). 

Thanks in advance.
Alexander.

**Comment by jdunkerley** [comment]
You can get around it by adding and app.config file redirecting to 2.6.4.14350:

```
      <dependentAssembly>
        <assemblyIdentity name="nunit.core.interfaces" publicKeyToken="96d09a1eb7f44a77" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.4.14350" newVersion="2.6.4.14350" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="nunit.core" publicKeyToken="96d09a1eb7f44a77" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.4.14350" newVersion="2.6.4.14350" />
      </dependentAssembly>
```

**Comment by AlexanderButs** [comment]
Thanks, man. It works.
But anyway, I think NUnit should be updated in AutoFixture package. If it is It will work out of the box without any manipulation (of course if you use latest stable version of NUnit).

**Comment by jdunkerley** [comment]
yep agree would be nice if just worked out the box.

**Comment by ploeh** [comment]
*Working out of the box* completely depends upon the box. Some people have one combination of software installed, and some people have another combination.

By keeping the version as conservative as possible, we enable those not running the latest and greatest software to also derive value from AutoFixture - and those who do run the latest and greatest can apply binding redirects.

The converse isn't true. If AutoFixture.NUnit2 was always compiled against latest versions of all dependencies, we'd be artificially preventing some users from using it. Such users may not be able to run the latest and greatest because of dependency issues with other packages they use.

That said, the NuGet package ought to have executed the `Add-BindingRedirect` command automatically upon installation, but this may have broken with the new version of NuGet...

If someone feels like looking into whether or not the install script no longer works, it would be a help :wink:

**Comment by AlexanderButs** [comment]
I totally agree with You. Also You are doing great stuff, thanks for that.
But anyway, NUnit 2.6.4 is two years old, I think it's a standard defacto for this particular framework, even resharper team uses it to run tests. I don't ask You to integrate NUnit 3.0 which came out few weeks ago, but NUnit 2.6.4 integration is appreciated.
Of course I can do it my self but for me is "spent two days to deal with all this stuff" and for You is "spend 15 minutes".
Anyway thanks for Your reply. =)

**Comment by zvirja** [comment]
Just for the reference, the final `App.config` file should look like:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="nunit.core.interfaces" publicKeyToken="96d09a1eb7f44a77" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.4.14350" newVersion="2.6.4.14350" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="nunit.core" publicKeyToken="96d09a1eb7f44a77" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.6.4.14350" newVersion="2.6.4.14350" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
