### ISSUE TITLE
"Continuous Delivery" in CONTRIBUTING.md needs updating

### ISSUE THREAD

**Issue by tiesmaster** [AutoFixture/AutoFixture#504]
After moving to AppVeyor (#456), the reference to TeamCity is not correct anymore. I'm happy to update the section, but I don't know if the other stuff is still valid.

**Comment by moodmosaic** [comment]
Thank you for catching this! – It'd be fine to update the section :+1: 

FWIW, I don't see any new release in [AutoFixture downloads section on CodePlex](https://autofixture.codeplex.com/releases/view/353237) after the end of 2014...

**Comment by ploeh** [comment]
> FWIW, I don't see any new release in AutoFixture downloads section on CodePlex after the end of 2014...

Correct. CodePlex was becoming too unstable, so I disabled that publication a long time ago. No one has complained since.

**Comment by ploeh** [comment]
I've been postponing this because our entire build process has been undergoing some changes. With #523 we're moving towards a new build script based on FAKE.

That's not the build script used by the AppVeyor build, though, so we're going to need to change the build server as well.

As described in #530, I'm currently evaluating the new build script, so I think we should still wait until it stabilises before moving on with this issue.

**Comment by ploeh** [comment]
Once #551 is completed, I think we ought to be ready to update the documentation as well.

**Comment by ploeh** [comment]
Since #551 is now completed, we ought to update the documentation now.

**Comment by ecampidoglio** [comment]
I updated the documentation in d9da7ec. Feel free to complement it with more information if you find that something is missing.

**Comment by ploeh** [comment]
I've added a few more updates to the CONTRIBUTING file. AFAICT, this should address the various issues mentioned here, so I'm going to close the issue.

If there are remaining problems, please write to us about them, or better yet, send a pull request.
