### ISSUE TITLE
Connect AutoFixture with NUnit3

### ISSUE THREAD

**Issue by hackle** [AutoFixture/AutoFixture#522]
The much endeared [AutoData] feature of AutoFixture has yet to be connected to the shiny new NUnit 3, introducing a unnecessary dilemma for many of us:  AutoFixture or NUnit3?

In order to bridge the gap I have ventured a solution:

https://github.com/hackle/AutoFixture.NUnit3.AutoDataConnector

It'll be awesome if with the help of AutoFixture supporters, this somewhat naive attempt could develop into a new component of AutoFixture to enable it to stay up-to-date.

I've also particularly tested that it works under Resharper 10.0.2 + NUnit 3, hopefully this puts an end to the woeful support from Resharper 9 + NUnit 2.6.*

**Comment by ploeh** [comment]
This could definitely be a welcome addition to the AutoFixture family. When the _AutoFixture.NUnit2_ package was created, we were fully aware that NUnit 2's extensibility model would make it awkward to use at best. We also expected that this would become better in NUnit 3, but that it would involve breaking changes. This is the reason we deliberately named the Glue Library _AutoFixture.NUnit2_, instead of simply _AutoFixture.NUnit_.

This means there's room for a brand-new, independently developed _AutoFixture.NUnit3_ package.

For anyone interested in contributing to a new _AutoFixture.NUnit3_ package, I think that @hackle's code can serve as a prototype. It's probably going to be easier to re-implement it than try to move the code wholesale; if for no other reason, then simply for the reason that I'm not going to review a big pull request in one go (more details [here](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests)).

The situation is similar to when the _AutoFixture.XUnit2_ package was created. After [an initial attempt with a big pull request](https://github.com/AutoFixture/AutoFixture/pull/294), we succeeded by instead breaking it up in several small pull requests, adding features as we went along.

Particularly, I'd like to draw attention to [this comment that explains the motivation for working incrementally](https://github.com/AutoFixture/AutoFixture/pull/294#issuecomment-82832126), and [this comment outlining a possible plan](https://github.com/AutoFixture/AutoFixture/pull/294#issuecomment-82385218). In the end, I think the progress of pull requests deviated a bit from the original plan, but they're all visible (among other pull requests) if you [search for them](https://github.com/AutoFixture/AutoFixture/pulls?page=2&q=is%3Apr+is%3Aclosed+xunit). I believe the first one was #373.

I'll be happy to review all pull requests of reasonable size, but I know next to nothing about NUnit 3, so I will welcome help from experts. Remember, reader, that if you wish to use AutoFixture with NUnit 3, it's in your best interest to help make it the best solution it can be :wink:

**Comment by ploeh** [comment]
A note for anyone happening by here: the [AutoFixture.NUnit3](https://www.nuget.org/packages/AutoFixture.NUnit3) NuGet package is now available. As I'm writing this, it's still a work in progress, as described in the [release notes](https://github.com/AutoFixture/AutoFixture/releases/tag/v3.41.0).

**Comment by ploeh** [comment]
Is there remaining work, or are we done?

**Comment by sergeyshushlyapin** [comment]
There is no `[NoAutoProperties]` attribute implementation so far (required to finish my PR about [attributes order](https://github.com/AutoFixture/AutoFixture/compare/master...sergeyshushlyapin:nunit3-attributes-order)).

**Comment by hackle** [comment]
Will get on it soon!

**Comment by ploeh** [comment]
Now that #611 is merged, should we close this issue?

**Comment by ploeh** [comment]
Completed in [AutoFixture.NUnit3 3.45.0](https://www.nuget.org/packages/AutoFixture.NUnit3/3.45.0).
