### ISSUE TITLE
Augment the IFixture interface with the Repeat function from the Fixture class

### ISSUE THREAD

**Issue by SeanFarrow** [AutoFixture/AutoFixture#539]
It would be good if the IFixture interface provided access to the repeat function from the fixture class..

I'm using JustBehave and they've recently changed there CreateFixture method to take an IFixture instead of a Fixture so now the repeat method from the Fixture class is unavailable. I'm happy to do the work and provide a pull request.
Any thoughts/objections to this?

**Comment by moodmosaic** [comment]
I haven't heard about JustBehave, though [there is a RepeatCount member](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/IFixture.cs#L35) on the `IFixture` interface...

**Comment by SeanFarrow** [comment]
Hi,

 

I am aware of RepeatCount, but I’m looking to add the IEnumerable<T Repeat(Func<T> function) member to the IFixture interface.

Cheers

Sean.

**Comment by moodmosaic** [comment]
Isn't that already possible with `Generator<T>`? An example can be found [here](http://stackoverflow.com/a/17170033).

**Comment by ploeh** [comment]
Thank you for writing, and for your interest in AutoFixture. It's always wonderful to hear that someone is using the library, even if we often learn about it when things work less than stellar :smile: 

Unfortunately, changing an interface (including adding new members) is a breaking change, so we can't do that in AutoFixture 3. It'd be possible to do that in [AutoFixture 4](https://github.com/AutoFixture/AutoFixture/milestones/4.0), but I'd be inclined to think that the change isn't warranted.

I've had my eye on the entire `IFixture` interface for years, because I find it crude, but I must admit that it seems to work. Still, I'd be reluctant to _add_ more members to it.

If you consider the implementation of the particular `Repeat` method, however, it wouldn't have to be specific to the `Fixture` class:

```C#
public IEnumerable<T> Repeat<T>(Func<T> function)
{
    return from f in Enumerable.Repeat(function, this.RepeatCount)
            select f();
}
```

Would it be possible, instead, to move it to an extension method like the following?

```C#
public static IEnumerable<T> Repeat<T>(this IFixture fixture, Func<T> function)
{
    return from f in Enumerable.Repeat(function, fixture.RepeatCount)
            select f();
}
```

I haven't tried the above, so it's possible that there's a flaw in my reasoning.

All that said, though, I can't recall ever having used that function, so I wonder why it's even there... Why do you need it?

**Comment by SeanFarrow** [comment]
Hi Mark,

 

I understand it’s a breaking change.

What I’m using Repeat for is to create a number of interfaces (IPropertyDifferenceApplierStrategy in this case) and set properties on each of them.

Is there a better way to do this without repeat.

I waqs trying to avoid writing my own generator/customization!

If not, it certainly would be possible to convert Repeat to an extension method on IFixture, indeed, that’s the approach I came up with earlier this morning.

Cheers

Sean.

**Comment by ploeh** [comment]
If we can move the method to an extension method, I don't think it'd be a breaking change, so I'd definitely consider that a viable option.

**Comment by SeanFarrow** [comment]
I’d be happy to do that and submit a pr.

Cheers

Sean.

**Comment by ploeh** [comment]
:+1:

**Comment by ploeh** [comment]
With the release of [AutoFixture 3.43.2](https://www.nuget.org/packages/AutoFixture/3.43.2), can we now close this issue?

**Comment by SeanFarrow** [comment]
Yes.
