### ISSUE TITLE
Add `DoAfter` to `IPostprocessComposer`?

### ISSUE THREAD

**Issue by JoshMcCullough** [AutoFixture/AutoFixture#544]
After a specimen is created, I'd like an opportunity to "clean up things". E.g., let's make sure that the auto-generated `StartDate` is less than the auto-generated `EndDate`:

```
fixture.Customize<MyThing>(c => c
    .DoAfter(o =>
    {
        if (o.EndDate < o.StartDate)
            o.EndDate = o.StartDate.AddDays(2);
    }));
```

I tried to do this with `Do`, but it seems to happen _before_ the properties are filled.

**Comment by ploeh** [comment]
I wonder if it's a bug that `Do` executes _before_ properties are filled, or if it's by design. It's more than three years ago I wrote that feature, and I can no longer recall :flushed: 

The fact that I don't know should be a strong clue to the fact that I never use the fluent DSL of AutoFixture.

Still, I'm willing to entertain the notion that it is, indeed, a bug, but I could imagine that other users might rely on the this behaviour...

All that said, though, I find AutoFixture's fluent DSL complex enough already, so I don't want to add more features to it. I think that the API is valuable, because it provides an easy way to get started with AutoFixture. On the other hand, it was never the intent that it should enable you to do _everything_. Occasionally, we get requests like these, to enhance the API, but if we followed every suggestion, we'd eventually have to turn the DSL into a Turing-complete language in itself. First, I don't think I'd be able to do that, and second, I don't think it adds any value, given that AutoFixture is already 'hosted' by a Turing-complete language (C#, Visual Basic, F#).

That doesn't mean that you're out of luck, though. There are [lots of options for addressing the particular situation with start and end dates](http://stackoverflow.com/a/28633780/126014).

HTH

**Comment by ploeh** [comment]
BTW, I've closed this issue mainly because I don't think it's a good idea to add more members to the fluent DSL.

It doesn't mean that I'm closing the conversation. If you need further assistance, feel free to ask :smile: 

Additionally, anyone reading this and deciding to investigate the whole `Do`-happens-before-auto-properties issue should feel free to look into the issue. I'm not sure the exact order of execution is specified anywhere; neither in tests nor in documentation...

**Comment by JoshMcCullough** [comment]
Thanks for the detailed response. If I remember, next week, I'll try to look into the order just out of curiosity. I'll look into the link you included.

**Comment by tiesmaster** [comment]
I have a lot of code that does this:

````csharp
    fixture
       .Build<MyClass>()
       .Without(x => x.SomeProp)
       .Do(x => x.SomeProp = x.DependentProp)
       .Create();
````

So the `Do()` will always need to be accompanied with a `Without()`, otherwise it will be overwritten. I thought, that the order was by design, so never bothered to put in an issue. But for me it doesn't really make sense to do the auto properties, if you're going to override it anyhow.

I'd love to see the two switched, so you don't need the `Without()` anymore. Since, the behavior doesn't seems to be documented, I wouldn't have any objections to changing it.

**Comment by ploeh** [comment]
FWIW, the original intention with `Do` was mostly to enable you to call _methods_...
