### ISSUE TITLE
IReadOnlyDictionary can only be enumerated once

### ISSUE THREAD

**Issue by mattklein999** [AutoFixture/AutoFixture#591]
I'm using AutoFixture to ensure all of our messages can be serialized and deserialized.

I am using reflection to get all of our messages, giving the type to AutoFixture to create an instance, sending that instance into our serializer, sending the result into the deserializer, and then, comparing all properties on the AutoFixture instance to the properties on the deserializer instance.

This was working well until we added an IReadOnlyDictionary<> type to one of our messages. AutoFixture creates the type fine, it get serialized/deserialized just fine, but then fails on the comparison because the second iteration of the IReadOnlyDictionary yields no result.

Here is minimal test to show the issue. I tested against AutoFixture 3.43 in VS 2013 using .NET 4.5.

        [TestMethod]
        public void Create_WithAutoConfiguredMoqCustomization_GivenReadOnlyDictionary_CanEnumerateTwice()
        {
            var fixture = new Fixture();
            fixture.Customize(new AutoConfiguredMoqCustomization());
            var t = fixture.Create<IReadOnlyDictionary<string, string>>();

            var t1 = t.ToList();
            var t2 = t.ToList();

            Assert.IsTrue(t1.SequenceEqual(t2));
        }

I also tried using `AutoConfiguredNSubstituteCustomization` with the same results.

**Comment by moodmosaic** [comment]
When requesting an interface like `IReadOnlyDictionary`, the request goes through the customization and that invokes the auto-mocking Glue Librarie(s).

The easiest thing to do is to change `IReadOnlyDictionary` to `ReadOnlyDictionary` and the test should pass, as the following passing test demonstrates:

```c#
[Fact]
public void ReadOnlyDictionaryCanBeCreated()
{
    var fixture = new Fixture();
    var actual = fixture.Create<ReadOnlyDictionary<string, string>>();
    Assert.NotNull(actual);
}
```

**Comment by ploeh** [comment]
An interface is only type-safe guarantee about a 'shape'; it's [not a contract](https://blogs.msdn.microsoft.com/kcwalina/2004/10/24/api-design-myth-interface-as-contract).

As @moodmosaic points out, if you want the interface to exhibit certain behaviour, you're essentially looking for a [_Fake_ rather than a _Stub_](http://www.martinfowler.com/bliki/TestDouble.html). Nothing wrong with that, but you can map `IReadOnlyDictionay` to `ReadOnlyDictionary` using a `TypeRelay`.

All that said, users of AutoFixture were often surprised by the 'non-intuitive' behaviour of well-known collection interfaces like `IEnumerable<T>` etcetera, so in AutoFixture 3, we added 'intuitive' behaviour for well-known collection interfaces. We may have missed some interfaces, though, but it's a little more complicated than that.

As an example, `IReadOnlyCollection<T>` isn't supported in AutoFixture 3, because the interface was first defined in .NET 4.5, and AutoFixture 3 only targets .NET 4. It could be that the same is the case for `IReadOnlyDictionary`, but I don't have time to research that right now (because I'm travelling, with only occasional internet access).

**Comment by mattklein999** [comment]
Thanks @moodmosaic, using `ReadOnlyDictionary` instead of `IReadOnlyDictionary` works perfectly just as you suggested. I feel silly for not considering that...

And thanks to comments by @ploeh which led me to find out that we could also use either
`fixture.Register<IReadOnlyDictionary<string,string>>(() => new Dictionary<string, string>());`
or
`fixture.Inject<IReadOnlyDictionary<string,string>>(new Dictionary<string, string>());`
in lieu of the auto mock customization.

Thank you both!

**Comment by moodmosaic** [comment]
@mattklein999, here's also a `TypeRelay` example of what @ploeh [suggested](https://github.com/AutoFixture/AutoFixture/issues/591#issuecomment-204723745):

```csharp
[Fact]
public void IReadOnlyDictionaryCanBeCreatedViaTypeRelay()
{
    var fixture = new Fixture();
    fixture.Customizations.Add(
        new TypeRelay(
            typeof(IReadOnlyDictionary<string, string>),
            typeof(ReadOnlyDictionary<string, string>)));

    var actual = fixture.Create<IReadOnlyDictionary<string, string>>();

    Assert.NotNull(actual);
}
```

That allows you to keep using `IReadOnlyDictionary` dictionary in your tests, if you need to.
