### ISSUE TITLE
AutoFixture hangs when creating an enum that has no defined values

### ISSUE THREAD

**Issue by lowds** [AutoFixture/AutoFixture#594]
Given the following:
```
public class MyClass
{
    public EmptyEnum MyProperty { get; set; }
}

public enum EmptyEnum
{
    //having no values here will break AutoFixture
}
```

When creating an instance of MyClass using 
```
var result = new Fixture().Create<MyClass>();
```

AutoFixture will hang until the process is manually killed.

----

The issue lies within the EnumGenerator class; the RoundRobinEnumEnumerable.GetEnumerator method will continually loop without ever hitting the yield return statement.

Question here is what would be the best thing to do in such instances - I'm thinking the RoundRobinEnumEnumerable constructor could throw an InvalidOperationException if an enum has no values?  If an appropriate exception message was thrown then would allow the caller to fix their code, perhaps something like:

> Cannot create a value for EmptyEnum as the enum has no values defined

**Comment by moodmosaic** [comment]
Thank you for reporting this! It looks like a bug, and the problem seems to be in [this](https://github.com/AutoFixture/AutoFixture/blob/25dd256158b7f2ca7869e4fa9d6429c9e5c045ce/Src/AutoFixture/EnumGenerator.cs#L97-106) method, as you've correctly spotted :+1:

I haven't done a thorough investigation, but I think that using an `if` conditional *may* solve the problem:
 
```
public IEnumerator GetEnumerator()
{
    if (this.values.Any())
    {
        while (true)
        {
            foreach (var obj in this.values)
            {
                yield return obj;
            }
        }
    }
}
```

Would you care to give it a shot and submit a Pull Request? :smiley:
