### ISSUE TITLE
Guard clause assertion treating static class as abstract.

### ISSUE THREAD

**Issue by mmkal** [AutoFixture/AutoFixture#612]
I may be doing something wrong here, but it looks like there's a bug somewhere in the GuardClauseAssertion class in AutoFixture.Idioms. I'm trying to use it to test that all arguments passed into a method in a static class are null-checked, but AutoFixture seems to be trying to instantiate the class (even worse, it seems to think it's abstract). Here's a small demo:
```csharp
public interface IMyInterface { }

public static class MyStaticClass
{
    public static void MyMethod(this IMyInterface myInterface)
    {
        if (myInterface == null) throw new ArgumentNullException(nameof(myInterface));
    }
}
public class MyNonStaticClass
{
    public static void MyMethod(IMyInterface myInterface)
    {
        if (myInterface == null) throw new ArgumentNullException(nameof(myInterface));
    }
}
public class TestClass
{
    public static IEnumerable<object[]> TypesToTest => new[] 
    {
        typeof(MyStaticClass),
        typeof(MyNonStaticClass)
    }.Select(t => new[] { t });

    [Theory]
    [MemberData(nameof(TypesToTest))]
    public void GuardClause_UsingAutoMoq(Type type)
    {
        var fixture = new Fixture().Customize(new AutoConfiguredMoqCustomization());
        var guardClauseAssertion = new GuardClauseAssertion(fixture);
        guardClauseAssertion.Verify(type.GetMethods());
    }

    [Theory]
    [MemberData(nameof(TypesToTest))]
    public void GuardClause_ManuallyInjectDependency(Type type)
    {
        var fixture = new Fixture();
        IMyInterface myInterface = Mock.Of<IMyInterface>();
        fixture.Inject(myInterface);
        var guardClauseAssertion = new GuardClauseAssertion(fixture);
        guardClauseAssertion.Verify(type.GetMethods());
    }
}
```
The tests pass when verifying MyNonStatic class, but they fail for MyStatic class with the following exceptions:
For GuardClause_UsingAutoMoq, it throws `System.NotSupportedException: parent does not have a default constructor. The default constructor must be explicitly defined.`

For GuardClause_ManuallyInjectDependency, it throws `Ploeh.AutoFixture.ObjectCreationException: AutoFixture was unable to create an instance from MyStaticClass because it's an abstract class.`

This seems wrong to me because:
1. MyStaticClass is not an abstract class, it's a static class.
2. For MyNonStaticClass, which has exactly the same implementation of MyMethod as MyStaticClass, the tests pass.

I think I have seen slightly different behaviour when the parameters of the static method are concrete types, but that may be a separate issue.

Am I doing something strange here, or is this a legitimate bug?

**Comment by ploeh** [comment]
Thank you for supplying this detailed repro :+1: It does, indeed, look like a bug.

FWIW, it isn't entirely incorrect that the class is abstract, because that's actually [what it compiles to](http://dotneteers.net/blogs/divedeeper/archive/2008/08/04/QueryingStaticClasses.aspx) when using the C# `static` keyword in this fashion.

The defect in `GuardClauseAssertion` is that it attempts to verify all members on the supplied class, including the members it inherits; that is: `Equals`, `ToString`, and `GetHashCode`. These are all instance members, so in order to invoke them, `GuardClauseAssertion` attempts to create an instance of the class.

In fact, we've already added a filter for `Equals` in `Verify(MethodInfo)`, but there's no filter for `ToString` or `GetHashCode`. So far, it hasn't been necessary because these two methods take no arguments, and therefore, there are no arguments to guard.

It seems to me that the fix ought to be to add similar filters for these two inherited methods.

Until such a fix is available, here's a workaround:

```C#
[Theory, MemberData(nameof(TypesToTest))]
public void Workaround(Type type)
{
    var fixture = new Fixture();
    fixture.Inject(new Mock<IMyInterface>().Object);
    var guardClauseAssertion = new GuardClauseAssertion(fixture);
    guardClauseAssertion.Verify(
        type.GetMethods().Where(mi => mi.DeclaringType == type));
}
```

**Comment by mmkal** [comment]
Thanks, that workaround solves my problem, is pretty clean, and it's probably what I should be doing anyway - bug or not, it's a bit weird to be verifying a list of 5 methods when I only care about 1.

Incidentally, I'm also seeing GetType() in the method list. I'm guessing the filter for that one isn't required because it's non-virtual?

**Comment by ploeh** [comment]
I forgot about `GetType` when I wrote the above response :flushed:

**Comment by mmkal** [comment]
Ah, ok :). Thanks very much for the help!
