### ISSUE TITLE
Fill SortedDictionary

### ISSUE THREAD

**Issue by ploeh** [AutoFixture/AutoFixture#623]
When you ask AutoFixture for a dictionary, it provides a non-empty value:

```C#
var fixture = new Fixture();
var actual = fixture.Create<IDictionary<int, string>>();
Assert.NotEmpty(actual); // Succeeds
```

When you request a sorted dictionary, on the other hand, the returned collection is empty. This test fails its assertion:

```C#
var fixture = new Fixture();
var actual = fixture.Create<SortedDictionary<int, string>>();
Assert.NotEmpty(actual); // Fails
```

Since AutoFixture can already supply non-empty dictionaries, and one of the constructor overloads for `SortedDictionary<TKey, TValue>` takes a dictionary, it ought to be fairly easy to add a _relay_ from `SortedDictionary<TKey, TValue>` to `IDictionary<TKey, TValue>`.

The implementation could for example be a new `ISpecimenBuilder` that handles requests for any `SortedDictionary<TKey, TValue>` by resolving `IDictionary<TKey, TValue>` from the `context`, and then invoking the appropriate constructor overload with the returned value.

Another implementation option is to mimic the way concrete dictionaries are already filled. See the combination of `DictionaryFiller` and `DictionarySpecification` in the `Fixture` class.

**Comment by ploeh** [comment]
See also #622 and #624.

**Comment by rahulpnath** [comment]
@ploeh Do you have any thoughts on how to support custom comparer for the SortedDictionary Key. 

I just started on with [this] (https://github.com/rahulpnath/AutoFixture/pull/1). It works fine for types that have a default comparer, but fails for complex types, objects etc. Would going down creating a custom request object with the comparer as a property be the right path.

**Comment by ploeh** [comment]
Could the feature be implemented similar to ##629? Since that implementation chose the _Specification_ options, I'd prefer it if this and #622 use the same approach, if at all possible.

**Comment by rahulpnath** [comment]
@ploeh Cool will use the Specification approach. But even with the sorted set specification approach, I don't see how this would work?

var result = fixture.Create<SortedSet<object>>();

It fails with below error (as expected)
Test 'Ploeh.AutoFixtureUnitTest.FixtureTest.CreateSortedSetReturnsCorrectResult' failed: System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
---- System.InvalidOperationException : Failed to compare two elements in the array.
-------- System.ArgumentException : At least one object must implement IComparable.

Is that the expected behavior?

**Comment by ploeh** [comment]
What is it creating?

**Comment by rahulpnath** [comment]
@ploeh Sorry missed that on paste

var result = fixture.Create<SortedSet<object>>();

Any type without a default comparer.

**Comment by ploeh** [comment]
Is the situation different from when one requests `IDictionary<TKey, TValue>`?
