### ISSUE TITLE
Setting non-public properties

### ISSUE THREAD

**Issue by IanKemp** [AutoFixture/AutoFixture#660]
Please refer to http://stackoverflow.com/questions/5722581/autofixture-how-do-i-call-a-method-how-to-set-a-private-setter-of-an-autoprop and http://autofixture.codeplex.com/workitem/4200 - it appears that at some stage there was an intention to allow AutoFixture to set non-public properties, but I'm not sure what, if anything, was done regarding that.

Is setting non-public properties currently possible (and if so, how); if not, is there any intention of implementing this functionality, and if so when?

**Comment by ploeh** [comment]
Those linked discussions are old, and AutoFixture's internal architecture has undergone several changes since then. There are no current plans to enable population of non-public members in AutoFixture itself, for the reason that [tests should only exercise the public API of the System Under Test](http://blog.ploeh.dk/2015/09/22/unit-testing-internals).

AutoFixture does most of its work using Reflection, so you could probably replace the auto-property part with one that also sets non-public properties. If you want to make it a wholesale replacement, I'm not going to claim that that's going to be easy, but if you only need to set non-public properties on a few, specific objects, it ought to be doable.

**Comment by IanKemp** [comment]
I understand and agree that we should only test the public API, but unfortunately I have a large body of code with a lot of private properties and no tests, and superiors who won't allow refactoring unless I can prove I haven't broken the functionality... which requires tests to be written. Catch-22.

From what you are saying, the only way to get the functionality I need is by grabbing the AutoFixture source and modifying it as necessary. That's not a major problem, although I do wish it was simpler. Thanks for your reply.

**Comment by ploeh** [comment]
> grabbing the AutoFixture source and modifying it as necessary

That's obviously an option, and may, in fact, be the easiest way, if it's mostly for that one time. Otherwise, you may also be able to create a custom class and replace [AutoPropertiesCommand](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Kernel/AutoPropertiesCommand.cs) with it. That's most likely the class you're going to need to modify anyway.

If you have such a class (let's call it `AutoPrivatePropertiesCommand`, you may be able to do the swap using the extensibility mechanisms provided by AutoFixture, so that you can still use the rest of AutoFixture via the published NuGet packages. That's probably a more viable long-term plan.

**Comment by ploeh** [comment]
All that said, though, I'd like to add a few comments to the overall situation. If you find these comments useless and out of touch with reality, then feel free to ignore them.

> superiors [...] won't allow refactoring unless I can prove I haven't broken the functionality

I see. Will those same superiors allow you to address defects or develop new code on that code base?

Also, changing accessibility modifiers of properties in itself doesn't change behaviour. Do you need tests in order to prove that?

**Comment by govorovvs** [comment]
`public int SomeProperty { get; set; }`
is a public API to the same extent as
`public int SomeProperty { get; private set; }`
so I don't understand why you resist this changes. Most of developers will find AutoFixture more and more useful if it will support non-public properties. In my cases I try to use AutoFixture for testing domain model entities, but classic domain paradigm requires non-public setters for properties, so AutoFixture can't help me in my cases.

**Comment by ploeh** [comment]
@govorovvs, thank you for writing.

A C# property is, in fact, syntactic sugar over a set of methods. `public int SomeProperty { get; set; }` [compiles to two methods](http://stackoverflow.com/a/23102679/126014).

The same can be said of `public int SomeProperty { get; private set; }`, but here, the setter compiles to a private method, while the getter compiles to a public method.

Therefore, the setter is not part of the public API, and as explained above, AutoFixture will not call non-public members out of the box.

HTH

**Comment by zvirja** [comment]
Closing this one, as I agree with what @ploeh wrote above so we will likely not support filling of the properties with private setters. If wish to have that behavior, feel free to customize AutoFixture.

**Comment by NooNameR** [comment]
https://github.com/AutoFixture/AutoFixture/pull/1075 will make it works :)
