### ISSUE TITLE
Better support for Discriminated Unions

### ISSUE THREAD

**Issue by asik** [AutoFixture/AutoFixture#683]
I noticed that:
```fsharp
type DU = A | B | C

[<Fact>]
let ``Autofixture only ever creates the first case of a DU`` () =
    for i = 1 to 1000 do
        let du = fixture.Create<DU>()
        match du with
        | A -> ()
        | _ -> Assert.True false
```

That's too bad because for enums (another sum type) it'll create any value just fine. I'm no expert user of AutoFixture and unsure of where to go from here, is there some F# extension or other workaround I can use? In any case it would be nice if this was supported out of the box.

**Comment by moodmosaic** [comment]
That sounds like an enhancement to me, though I'm not totally sure—could it be a bug instead? :confused:

---

The most quick & naive workaround I can think of, is to use a custom `ISpecimenBuilder`, like so:

```f#
type DU = 
    | A
    | B
    | C

let duBuilder = 
    let elems = 
        typeof<DU>
        |> FSharpType.GetUnionCases
        |> ElementsBuilder

    { new ISpecimenBuilder with
            member this.Create(req, ctx) = 
                match req with
                | :? Type as typ
                        when FSharpType.IsUnion typ && typeof<DU> = typ
                    -> FSharpValue.MakeUnion(
                           elems.Create(typeof<UnionCaseInfo>, ctx) :?> _, [||])
                | _ -> NoSpecimen() :> _ }
```

Add `duBuilder` to the `Fixture` instance, as shown below:

```f#
let fixture = Fixture()
fixture.Customizations.Add duBuilder
```

Then, applying `fixture.Create<DU>()` 1000 times produces the following output on my machine:

```
A
B
C
B
C
A
A
C
B
B
C
A
B
C
A
B
A
C
B
C
A
C
B
A
B
C
A
A
B
C
A
C
B
B
A
C
A
C
B
C
B
A
A
B
C
C
B
A
C
B
A
B
C
A
A
B
C
A
C
B
B
A
C
C
B
A
B
C
A
B
A
C
A
B
C
C
B
A
C
B
A
C
B
A
C
B
A
C
A
B
C
A
B
A
C
B
B
C
A
B
```

**Comment by ploeh** [comment]
It's not a bug. F# discriminated unions are compiled as small inheritance hierarchies, where the base class has static factory methods for creating each of the union cases.

One of the heuristics AutoFixture uses to create values is to look for a static factory method if no public constructor is available. My guess is that this is what happens here. This heuristic picks the same factory method every time AutoFixture runs. This means that for the degenerate case reported here, you'll always get the same value.

While we could think of a couple of options to change this behaviour to support discriminated unions better, I wouldn't consider it of much value.

If you're writing tests in F#, I'll strongly recommend that you use [FsCheck](https://fscheck.github.io/FsCheck) instead of AutoFixture. It supports discriminated unions and other F# types much better, and has a much more F#-friendly API. I use it myself for all tests written in F#.
