### ISSUE TITLE
Upgrading to NuGet 3.0: AutoFixture xUnit Theory Does Not Get Discovered

### ISSUE THREAD

**Issue by Mike-EEE** [AutoFixture/AutoFixture#687]
I have recently upgraded my solution projects to NuGet 3.0 (from packages.config to project.json).  Everything seems to work with the exception of xUnit Theory with AutoFixture applied to it.  I have created a very simple example of this here:
https://github.com/Mike-EEE/Stash/tree/master/ReSharper.NuGet30

If you try building, you should, uh, discover that the tests do not get discovered. :stuck_out_tongue: 

If you [comment out these lines](https://github.com/Mike-EEE/Stash/blob/master/ReSharper.NuGet30/ReSharper.NuGet30/Class1.cs#L7-L11) and try building again, the tests get discovered.

Is this a known issue?  Am I doing something terribly wrong?  Maybe a little of both? :smile:

**Comment by ecampidoglio** [comment]
[Answered](http://stackoverflow.com/a/38764154/26396) on StackOverflow.

However, it might be worth investigating whether NuGet _can) be configured to automatically add binding redirects without resorting to the installation script. Last time I checked it didn't but that was a while ago (#8).

**Comment by Mike-EEE** [comment]
Yes thank you so much @ecampidoglio!  Much appreciated.  I am thinking of opening an issue on xUnit as well to maybe update their documentation as well.  I can't believe I am the first person to run into this. :stuck_out_tongue: 

I am curious if NuGet has a UserVoice?  This seems like it would be a very very popular request.

**Comment by ecampidoglio** [comment]
No worries, happy to help :smile: 

This problem has nothing to do with xUnit. It's just that [AutoFixture.Xunit2](https://www.nuget.org/packages/AutoFixture.Xunit2) is compiled [against xUnit 2.0](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit.net2/packages.config#L3-L4), so you're going to need a binding redirect if you want to use it with [xUnit 2.1](https://www.nuget.org/packages/xunit/2.1.0).

As it turns out, NuGet does, in fact, [add assembly binding redirects automatically](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/VSMSBuildNuGetProjectSystem.cs#L752-L795) when using the regular package restore system within Visual Studio, unless [told not to in the configuration](https://github.com/NuGet/Home/issues/1147#issuecomment-150011864).

Of course, this doesn't work when using `project.json`, since the restore process [doesn't modify any files on disk](https://docs.nuget.org/Consume/ProjectJson-Intro#user-content-transitive-package-restore):

> At this point the project system picks up the assembly references and updates them in memory, without modifying any of the files on disk. The underlying mechanism for picking up these references is an addition to the common msbuild targets.

which also means no automatic binding redirects.

**Comment by Mike-EEE** [comment]
Awesome.  Thank you for taking the time to explain this @ecampidoglio.  I admit I get a little carried away and impatient when diving into something new and don't catch all the details.  You've been a tremendous help with and after the fact. :+1: 

I believe I have enough on my end to continue now.  Hopefully the ping to NuGet will inspire them to address this problem in the future.

And actually... this problem will go away once the next version of AutoFixture (4?) releases, correct?  It will be built against 2.1 (or 2.2, maybe?), so a redirect won't be necessary, will it?

**Comment by Mike-EEE** [comment]
FWIW, I have created an issue for assembly redirects on NuGet's board:
https://github.com/NuGet/Home/issues/3372

**Comment by zvirja** [comment]
@ecampidoglio Currently we are working on the `v4` branch and one of the tasks will be to rework out `nuspec` files to support .NET Core.

I also faced that for non-Core projects NuGet automatically adds binding redirects. Therefore, I'd say that we could safely remove the [Install.ps1](https://github.com/AutoFixture/AutoFixture/blob/master/Nuget/Install.ps1) file. Do you agree that we can? :) I it could happen that I just missed something.

**Comment by ecampidoglio** [comment]
@zvirja Yes, the [original issue](http://nuget.codeplex.com/workitem/1541) in NuGet has been fixed a long time ago (at least since 2013, according to the old [issue page](http://nuget.codeplex.com/workitem/1541)), so there is no reason to keep `Install.ps1` around.

**Comment by zvirja** [comment]
It doesn't seem that we should fix the issue somehow, as it's NuGet related. 

BTW, it looks a bit strange, as MSBuild/NuGet/VS should add binding redirection for both old and .NET Core based projects. For the latter ones this is done during the build [see here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection).

I'm closing this one. Feel free to re-open it if any actions is required and issue is specific to our packages.
