### ISSUE TITLE
MSTest2 support

### ISSUE THREAD

**Issue by frblondin** [AutoFixture/AutoFixture#704]
First of all, many thanks for this great library.

I am in the process of transitioning to MSTest2 and I needed a support of a declarative Autofac integration. I created the following project that you can integrate in Autofixture if you want: https://github.com/frblondin/AutoFixture.MSTest2

As you can see I used the AutoFixture.xUnit.net2 project as a starting point.

Note that this project has a dependency with another project that I created to improve the data injection management (MSTest.TestFramework.AdvancedDataRow).

**Comment by moodmosaic** [comment]
:+1:

Since we don't support MSTest and there are no plans to support MSTest2, and this isn't about some Pull Request, I'm going to close this.

Feel free to reopen this, or open a new issue, if something actionable or related arises in the future.  The URL provided in this issue is still searchable though, in case other people want to look at it, or use it.

**Comment by frblondin** [comment]
You are right, there was no question :-)

My question is the following: if I submit a pull request, is there any chance it will be merged or you are not interested in providing a support of MSTest2?

**Comment by moodmosaic** [comment]
I have a feeling that MSTest's extensibility model isn't a lot better than [what we've got with NUnit2](https://github.com/AutoFixture/AutoFixture/search?q=nunit2&state=closed&type=Issues&utf8=%E2%9C%93). Happy to be proven wrong though.

**Comment by frblondin** [comment]
I let you decide whether or not MSTest2 deserves being supported by Autofixture.

My 2 cents opinion is that even if MSTest2 is not better than other testing frameworks from your standpoint, it will likely be used by many projects as it will be pushed & supported by Microsoft.

My current problem is that XUnit2 is really too slow in my context (big solution for which test discovery takes 2 minutes with XUnit2 and 6 seconds with MSTest2, see this [link)](https://github.com/xunit/xunit/issues/964) so I'll probably switch to MSTest2 and I'd like to continue using Autofixture.

Again, I can do a pull request but I want to know if you are interested.

**Comment by moodmosaic** [comment]
IME, if we decide to take on a new unit-testing Glue Library, it's going to be easier (and faster) with a series of Pull Requests, like we [did with NUnit2](https://github.com/AutoFixture/AutoFixture/pull/294#issuecomment-82385218) [and NUnit3](https://github.com/AutoFixture/AutoFixture/issues/522).

Even *that* though won't probably be so easy due to the fact that currently there's a lot of duplicate code in *AutoFixture.NUnit2*, *AutoFixture.NUnit3*, *AutoFixture.xUnit.net*, and *AutoFixture.xUnit.net2* projects.

I can see, for example, the `FavorArraysAttribute`, `FavorEnumerablesAttribute`, and `FavorListsAttribute` on each of the projects, and there are other similar (not to say nearly identical?) files like this.

Moving forward with a series of Pull Requests for [MSTest V2](https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/17/taking-the-mstest-framework-forward-with-mstest-v2/) *may* first invoke the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)), to get rid of some duplicate code from the existing unit-testing Glue Libraries—a decision that has to wait until #703 is closed, IMHO.

---

>so I'll probably switch to MSTest2 and I'd like to continue using Autofixture.

That should be possible already [using the fork you've created](https://github.com/frblondin/AutoFixture.MSTest2), AFAICT. :smiley:
