### ISSUE TITLE
Generic methods in AutoNSubstitute

### ISSUE THREAD

**Issue by pipedreambomb** [AutoFixture/AutoFixture#720]
Long time user, first time etc. I've cloned this project to see if I can do something about the lack of automocking when it comes to generic methods. For instance, the following code would return null, even when using AutoConfiguredNSubstituteCustomization:

`MyEntity mappedEntityFromDto = new Fixture().Freeze<IMapper>().Map<MyEntity>(myDto)`

If it were a non-generic method, it would return a randomly generated MyEntity, which would negate null reference exceptions and thus make my tests nice and short and able to focus on other things. Instead, all my tests end up with a line like 

`fixture.Freeze<IMapper>().Map<MyEntity>(Arg.Any<MyDto>()).Returns(fixture.Create<MyDto>());`

However, now I've looked into the source, I find a test in `AutoConfiguredFixtureIntegrationTest` called `GenericMethodsAreIgnored` that seems to suggest this isn't a bug, but a feature. I just wondered why that is; is it a technical limitation, a design decision or just left undone and an opportunity for improvement?

It was worked on by @mrinaldi.

**Comment by mrinaldi** [comment]
The way the customization works, it has to setup all the methods before they are used. Since we cannot know the type parameter beforehand, we cannot setup generic methods.
I sent a PR to `NSubstitute` to better support `AutoFixture` and support this scenario, but it was never merged.
However, @Zvirja is trying to get from where I left it: https://github.com/nsubstitute/NSubstitute/pull/259
I didn't review his PR, but I'm hoping it extends `NSubstitute` in such a way that `AutoFixture` can support this scenario.

**Comment by Zvirja** [comment]
Yes, I'm continuing the @mrinaldi's idea and am adding a way to register custom auto-value provider to NSubstitute. This will give us generics for free, because NSubsitute will ask us for values ("passive" approach instead of "active" - how it's now). Therefore a bit of patience and time should solve this issue :)

**Comment by pipedreambomb** [comment]
@Zvirja Exciting! Keep us posted :)

**Comment by zvirja** [comment]
Is finally fixed in v4. We reworked the integration approach and now generic methods are fully supported. Will be able to consume that when we release v4.

@pipedreambomb Would appreciate if you early test that using our [private feed](https://github.com/AutoFixture/AutoFixture#vnext-feed).
