### ISSUE TITLE
Range attribute on Enum throws InvalidCastException

### ISSUE THREAD

**Issue by Jogge** [AutoFixture/AutoFixture#722]
I just encountered this issue:

```
public enum MyEnum
{
    First = 1,
    Second = 2,
    Third = 3,
}
```

```
public class MyEntity
{
    [Range(1, 3)]
    public MyEnum MyEnum { get; set; }
}

```
```
public class AutoFixtureVsEnumRangeAttribute
{
    public AutoFixtureVsEnumRangeAttribute()
    {
        var fixture = new Fixture();

        fixture.Create<MyEntity>();
    }
}
```

When creating MyEntity with AutoFixture it throws InvalidCastException and says "Invalid cast from 'Int32' to 'MyEnum'".

**Comment by cvbarros** [comment]
This is because AutoFixture's support for DataAnnotations (in order to make it easier to create valid model instances in tests) is trying to assign a created `Int32` to your property of type `MyEnum`.
So, with this behavior, AutoFixture tries to create the value *based on annotation first*, then on the target property type. The `Range` attribute expects integersm so that's what you get.

In order to disable this behavior, you can customize your fixture by adding a built-in customization such:

```C#
public class AutoFixtureVsEnumRangeAttribute
{
    public AutoFixtureVsEnumRangeAttribute()
    {
        var fixture = new Fixture();
        fixture.Customize(new NoDataAnnotationsCustomization());
        fixture.Create<MyEntity>();
    }
}
```
However, in this case I'd create a custom annotation for allowing only certain values from an enum instead of using a `Range`.

**Comment by moodmosaic** [comment]
You may read [this](https://github.com/AutoFixture/AutoFixture/issues/453#issuecomment-149463476) comment on why you're getting an error for ranges other than `Int` and `Double`.
