### ISSUE TITLE
TypeRelay or some other means to always use generic class for generic interface?

### ISSUE THREAD

**Issue by SurajGupta** [AutoFixture/AutoFixture#730]
How can I configure a `Fixture` so that any request to create an `IReadOnlyList<T>` or `IReadOnlyCollection<T>` uses a `List<T>` without having to customize for all possible `T`?

Similarly, I'd like `IReadOnlyDictionary<T,K>` to always be created as a `Dictionary<T,K>`

And perhaps related...is there a way to override an existing mapping?  For example, when I ask for an `IEnumerable<T>` I get back some custom Autofixture object that honors that interface.  I'd like to just get back a `List<T>`

**Comment by SurajGupta** [comment]
Anyone?  @ploeh, @Zvirja, @sergeyshushlyapin? (picked recent committers)

**Comment by sergeyshushlyapin** [comment]
@SurajGupta, you need to create new `ReadOnlyListRelay` and `ReadOnlyDictionary` Specimen Builders similar to the existing [ListRelay](https://github.com/AutoFixture/AutoFixture/blob/ab829640ed8e02776e4f4730d0e72ab3cc382339/Src/AutoFixture/Kernel/ListRelay.cs#L11) and [DictionaryRelay](https://github.com/AutoFixture/AutoFixture/blob/ab829640ed8e02776e4f4730d0e72ab3cc382339/Src/AutoFixture/Kernel/DictionaryRelay.cs#L11):

```csharp
[Fact]
public void CreateReadOnlyList()
{
  var fixture = new Fixture();
  fixture.Customizations.Add(new ReadOnlyListRelay());
  var readOnlyList = fixture.Create<IReadOnlyList<object>>();
  Assert.IsType<ReadOnlyCollection<object>>(readOnlyList);
}

internal class ReadOnlyListRelay : ISpecimenBuilder
{
  public object Create(object request, ISpecimenContext context)
  {
    if (context == null)
      throw new ArgumentNullException(nameof(context));

    var t = request as Type;
    if (t == null)
      return new NoSpecimen();

    var typeArguments = t.GetGenericArguments();
    if (typeArguments.Length != 1 ||
        typeof(IReadOnlyList<>) != t.GetGenericTypeDefinition())
      return new NoSpecimen();

    return context.Resolve(
        typeof(ReadOnlyCollection<>).MakeGenericType(typeArguments));
  }
}
```

Unfortunately it cannot be included into AutoFixture 3.x because it's based on .Net 4 whereas `IReadOnlyDictionary` is [available starting from .Net 4.5](https://msdn.microsoft.com/en-us/library/hh881542(v=vs.110).aspx#Anchor_4). You may track .Net upgrading progress in #404. But, it should not prevent you from applying the customization on your side.

**Comment by SurajGupta** [comment]
@sergeyshushlyapin - much appreciated!  I'll give that a spin.
