### ISSUE TITLE
test discover bug with Autodata in a base class

### ISSUE THREAD

**Issue by bklooste** [AutoFixture/AutoFixture#735]
```csharp
public class A
{
        [Theory]
        [AutoData]
        public void testsum_auto(int a )
        {
            var c = a + 1;
            Assert.False(false);
        }
}

public class B : A
{
// some tests
}
```

testsum_auto and tests after this are not discovered , comment out autodata / replace with inline data and its fine. 

It may have been introduced in the latest xunit release but i cant confirm that.

**Comment by bklooste** [comment]
likely due to Data Attribute now having different method to override.

**Comment by bklooste** [comment]
copying the latest code into my own autoatribute works so either its fixed already and not published to general release nuget or it has to do with autodata not being in the same assembly which seems unlikely.

**Comment by zvirja** [comment]
I've just tested that code on my environment and it appeared work fine. See details of my environment below.

`Packages.config:`
```xml
  <package id="AutoFixture" version="3.50.2" targetFramework="net452" />
  <package id="AutoFixture.Xunit2" version="3.50.2" targetFramework="net452" />
  <package id="xunit" version="2.2.0" targetFramework="net452" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net452" />
  <package id="xunit.assert" version="2.2.0" targetFramework="net452" />
  <package id="xunit.core" version="2.2.0" targetFramework="net452" />
  <package id="xunit.extensibility.core" version="2.2.0" targetFramework="net452" />
  <package id="xunit.extensibility.execution" version="2.2.0" targetFramework="net452" />
```

Code:
```csharp
public class InheritanceTestBase
{
    [Theory]
    [AutoData]
    public void testsum_auto(int a)
    {
        var c = a + 1;
        Assert.False(false);
    }
}

public class NestedClass : InheritanceTestBase
{
}
```

R# runner result:
![image](https://cloud.githubusercontent.com/assets/1074182/24975547/c0b73846-1fce-11e7-8582-4704b241384f.png)

Could you please clarify whether this issue is still reproducible? If so, could you please clarify more details. For instance, is that .NET Core project or not; are you able to repro it on a small empty project, etc.

Thanks.

**Comment by zvirja** [comment]
Closing this one due to inactivity. @bklooste Feel free to re-open the issue if it still happens.
