### ISSUE TITLE
Autodata with recursive

### ISSUE THREAD

**Issue by bklooste** [AutoFixture/AutoFixture#737]
I get "traversed object graph contains a circular reference" but since the data is from json a circ reference is not possible its just a tree of the same type.  There is some documentation on how to create a custom fixture but how to do this with Autodata  , its a bit ugly having my own AutoData impl attribute everywhere. 

Personally i think this type of hard warning should be optional not default - it places a lot of assumption on how you use the data . Now if it could detect and actual reference on objects surebut  a Node with Children of Node is a very common structure with no circ reference even though its possible.

**Comment by zvirja** [comment]
> but since the data is from json a circ reference is not possible its just a tree of the same type.

It isn't quite clear how JSON is related to the AutoFixture. If you use JSON parsing utilities, AF should have nothing to do with such objects creation.

If that issue is still actual to you, could you please provide a code sample which demonstrates case where circular dependencies are finite? From my understanding this guard was added because that would lead to stackoverflow when AutoFixture tries to create such an object graph. If it already appeared that during creation of the `ObjectA` we leaded to creation of the `ObjectB` which, in its turn, requires `ObjectA` creation, it doesn't seem that this loop could be broken somehow..

**Comment by zvirja** [comment]
@bklooste Could you please clarify whether this issue is still actual to you?

**Comment by bklooste** [comment]
Sorry for the delay  but basically create an object that references itself  eg class Node  { Node[] Children; } .. Auto fixture    gives an error of "traversed object graph contains a circular reference"  .  Im saying the default behaviour should be to allow this .. since most of these objects come from service Apis which cant have a circc reference..  If  you want to check for this you should explicitly ask Autofixture to fail on these.

**Comment by zvirja** [comment]
It seems that we have a bit different vision on the situation, so let me align that.

AutoFixture is the tool to generate a graph of objects. If `fixture.OmitAutoProperties == false`, after an object is created AutoFixture automatically populates all its writable public fields and properties. This process happens _recursively_, so it could happen that AutoFixture will fail with stack overflow if there is a cyclic reference.

The circular references is not something bad in the design of your architecture. It's absolutely legal to have references of the same type because you can point them to the existing objects and avoid infinity. However, AutoFixture generation algorithm always creates _a new object_ to populate a particular field/property, so it could easily fail with stack overflow. This is a design of the AutoFixture and for such situations you should Customize the object creation graph.

The exception you noticed is thrown to indicate that a circular reference occurred and we are about to fail. I can't imagine situation when this is a false positive. We shouldn't disable the exception throw itself, rather we should configure AutoFixture to avoid such situations. To do that you can use [Customizations](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#customize-type) and prevent the cyclic object creation from happening.

Let me know if you still see when this exception might be a false positive.

**Comment by zvirja** [comment]
Closing this one as you can customize this behavior as described [here](https://github.com/AutoFixture/AutoFixture/wiki/Examples-of-using-behaviors#omitonrecursionbehavior). Also, you can use [Customizations](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#customize-type) as it was mentioned above to work around the situation.

Let me know if you see a false positive in current mechanism, so we could investigate that.
