### ISSUE TITLE
Take action on members decorated with ObsoleteAttribute in v4 branch

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#744]
We should remove all the obsolete methods in the `v4` branch

**Comment by moodmosaic** [comment]
Removing all members decorated with [ObsoleteAttribute](https://msdn.microsoft.com/en-us/library/system.obsoleteattribute(v=vs.110).aspx) will, indeed, create a (desired) compiler error. It will be easier for the `v4` users though to know *what to do next*.

For this reason, I'd keep around the existing ObsoleteAttributes, but I'd pass `true` in [this](https://msdn.microsoft.com/en-us/library/961hff5d(v=vs.110).aspx) constructor so that the obsolete element usage generates a compiler error.

AFAICT, this will have the same effect as if those members where removed, and in addition to that, users will know *why* they're getting an error and it can be easier for them to figure out *what to do next*.

---

* In `v3` we produce compiler warnings:
  ```
  //    Example.cs(29,25): warning CS0618: 'Example.OldProperty' is obsolete: 
  //            'This property is obsolete. Use NewProperty instead.'
  ```
* In `v4` we can produce compiler errors:
  ```
  //    Example.cs(31,25): error CS0619: 'Example.CallOldMethod()' is obsolete: 
  //            'This method is obsolete. Call CallNewMethod instead.'
  ```
* In `v5` we can entirely get rid of the members decorated with ObsoleteAttribute:
  ```
  //    Example.cs(31,25): error CS1061: 'Example` does not contain a definition
  //            for `CallOldMethod()' and no extension method called (...)
   ```

**Comment by zvirja** [comment]
Makes sense. Likely, it's just how such large projects behave - you need to wait 2 versions before you could finally remove API.

But let's follow this plan.

**Comment by zvirja** [comment]
Proceeded for v4.
