### ISSUE TITLE
NNnit3 "no test found to run" when ctor throws or protected

### ISSUE THREAD

**Issue by sm-g** [AutoFixture/AutoFixture#754]
Given classes

```cs
class User {
  public User(int id)
  {
    if (id < 1)
       throw new ArgumentOutOfRangeException();
  }
}

class MappedUser{
  protected MappedUser(int id, string name) { ... }
  public static MappedUser Create() { ... }
}
```
and tests with `AutoData` using them.

NUnit3 test adapter and ctrl+R, ctrl+T does not show such tests. So I can write many tests, then change something in ctor and everything will be "ok".

I expected them to be visible and failing when try to run.

**Comment by sergeyshushlyapin** [comment]
JFI, NUnitTestAdapter might be [quite unstable](https://github.com/AutoFixture/AutoFixture/pull/676#issuecomment-237988041).

**Comment by zvirja** [comment]
@sm-g I've just tested your case using the following code:
```csharp
public class User
{
    public User(int id)
    {
        if (id < 1)
            throw new ArgumentOutOfRangeException();
    }
}

public class MappedUser
{
    protected MappedUser(int id, string name) {}
    public static MappedUser Create()
    {
        return null;
    }
}

public class Tests
{
    [Test, AutoData]
    public void UserTest(User user)
    {
        
    }

    [Test, AutoData]
    public void MappedUserTest(MappedUser user)
    {
        
    }
}
```

My setup:
- VS 2017 Update 3
- Target Framework - 4.6.1
- NUnit version - 3.8.1
- NUnit3TestAdapter versin - 3.8.0

I've opened the VS Test window and run all the tests. Result:
![image](https://user-images.githubusercontent.com/1074182/30061145-e66e212e-924e-11e7-8a3a-ec4332691e2c.png)

Notice, we know about the issue that VS runner cannot handle test cases with dynamic test name. See PR #709 for more detail.

Could you please verify:
- whether the issue is still present
- whether issue is specific to VS runner only (e.g. no issues in R#, console)
- whether the issue is that your tests are not being discovered, or that tests cannot be run as described [here](https://github.com/AutoFixture/AutoFixture/pull/676#issuecomment-237988041).

**Comment by zvirja** [comment]
@sm-g Any chance to review my answer? So we could decide what to do with this issue..

**Comment by sm-g** [comment]
Using you code (and same versions from Setup), I got FileNotFound exception ("nunit.framework, Version=3.0.5797.27539, Culture=neutral, PublicKeyToken=2638cd05610744eb") when run tests with testdriven.net, and nothing in TestExplorer. 

my setups as yours, and AutoFixture.NUnit3 - 3.51.0

However, when I remove any conditions from `User` ctor, nothing changes. Just no way to use `AutoData`.

**Comment by zvirja** [comment]
@sm-g Could you please attach the solution that causes the issue? Also specify the version of VS you use.

I don't have `TestDriven` and can test with VS runner only.

**Comment by sm-g** [comment]
http://ge.tt/8AldRym2 

VS 15.4

**Comment by zvirja** [comment]
@sm-g Thanks for sharing the project.

That happens because AssemblyBinding redirection generation is disabled in your project. That is not something specific to AutoFixture product itself - rather to how the .NET works.

To fix the issue add the following statements to the csproj file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{BE1E2536-4D83-428B-9760-54A135A71164}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>AutoFixtureRepro</RootNamespace>
    <AssemblyName>AutoFixtureRepro</AssemblyName>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    
    <!-- Enable binding redirection generation -->
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
...
```

After that everything will work fine. If you change the `User` constructor to always trigger the exception (i.e. without condition: `throw new ArgumentOutOfRangeException();`), the failed test will be still displayed in the VS Test Explorer:

![image](https://user-images.githubusercontent.com/1074182/31810282-d97e7560-b583-11e7-9512-b1ef62d5dcbf.png)

Let me know whether now the original issue is solved.

**Comment by sm-g** [comment]
Yes, thanks for that
