### ISSUE TITLE
Please provide support for dotnet core 1.0,1.1,2.0 with mstest as well

### ISSUE THREAD

**Issue by gagandeep531** [AutoFixture/AutoFixture#881]
Hi Team,

Please provide support for dotnet core 1.0,1.1,2.0 with mstest as well.

We are facing difficulty in writing the unit test case for the same in absence of autofixture support

**Comment by zvirja** [comment]
Could you please describe the issue in more detail? Currently AutoFixture doesn't provide any special support for MSTest (see #704). That is not specific to .NET Core - it's the same for .NET Framework.

However, you can still AutoFixture with MSTest by manually constricting the Fixture instance:

```
[TestMethod]  
public void SomeTest()  
{  
    // arrange
    var fixture = new Fixture();
    var value = fixture.Create<int>();
    var sut = new Sut();
    // act  
    sut.SetValue(value);
    // assert  
    Assert.AreEqual(value, sut.Value); 
}
```

If your issue is about .NET Core support in general (not specific to MSTest) - this is what we are currently working on. We already support .NET Core, but that hasn't been released yet. See #404 for more detail. I'd expect the release in upcoming weeks. If you wish to early access the next version, use our [preview feed](https://github.com/AutoFixture/AutoFixture#vnext-feed).

Let me know if I misunderstood your question.

**Comment by zvirja** [comment]
@gagandeep531 Any updates? 😉

**Comment by gagandeep531** [comment]
I want to create complex object instance without initializing it with any data. let’s say i want to auto populate all the properties of an employee object with default values which contain address object as well as manager object inside employee object.

Cheers,
Gagan

**Comment by zvirja** [comment]
> I want to create complex object instance without initializing it with any data.

That's exactly what this product does. However, you issue is named "Please provide support for dotnet core 1.0,1.1,2.0 with mstest as well.". Could you elaborate which exact support you requested? Is that specific to MSTest or to .NET Core or to both?

**Comment by gagandeep531** [comment]
I was not able to install auto fixture in vs 2017 professional using nuget package manager.It rollback changes after installation is dmfailed. My application is built on dotnetcore 1.1 and we will migrate it to 2.0 in coming week.

**Comment by zvirja** [comment]
OK, I got it. You request was about .NET Core support.

I'm going to perform `v4-rc1` release with .NET Core support later today, so you should be able to use AutoFixture.

Closing this one as no actions are actually required.

**Comment by gagandeep531** [comment]
Thanks Alex for your immediate support.

Cheers! 😀

**Comment by zvirja** [comment]
JFYI: [I released](https://twitter.com/AutoFixture/status/920623108863741953) v4 rc1 to the NuGet, so you can consume and use it.
