### ISSUE TITLE
Support TimeSpan type for the Range attribute

### ISSUE THREAD

**Issue by wertzui** [AutoFixture/AutoFixture#930]
I have the following Property

        [Range(typeof(TimeSpan), "00:00:00", "10675199.02:48:05.4775807")]
        public TimeSpan Length { get; set; }

This causes Autofixture to fail because internally it uses `Convert.ToType("00:00:00", typeof(TimeSpan))` to get the actual value.

I expect this to work also with DateTime and DateTimeOffset.

**Comment by zvirja** [comment]
Currently AutoFixture doesn't support ranges other than numeric. But we have the similar feature requests around:
- [support enums](722)
- [support strings](919)

Probably, it makes sense to review the whole approach we currently have. It appeared that `DataAnnotations` support takes a significant part of the AutoFixture and it will start to take even more if we start to support more `Range` types or even new attributes (like [`Min/MaxLength`](678)).

We also know that this feature leads to the performance issues, that's why we have the [NoDataAnnotationsCustomization](https://github.com/AutoFixture/AutoFixture/blob/c856cd669ad0b9749edd238a304b5b4a7a901a76/Src/AutoFixture/NoDataAnnotationsCustomization.cs#L18), however likely not all the users know about it. I believe that most people don't use this feature, however still pay for it.

In order to support annotations the AutoFixture needs to depend on `System.ComponentModel.Annotations` and likely will start to depend on `System.ComponentModel.TypeConverter` as we need that in #930 to provide a good conversion API.

I'm just thinking that it's probably a good time to think about our further strategy for this feature. Basically, the question is whether we still want to maintain that inside the AutoFixture, or it's probably make sense to extract that to a separate project like `AutoFixture.DataAnnotations`. Given the size of the feature, it looks like a standalone module, which users should manually install and enable if they need. Of course, that is a breaking change, but we are still building the v4, so we could make that change.

The benefit will be that we'll be more permissive in accepting the new range support, without worrying that it blows up the AutoFixture. Instead, it will blow up the `AutoFixtuer.DataAnnotations` package, but that's totally fine, as this module is designed for exactly that functionality.

@moodmosaic What do you think about that? I'm raising this question basically I started to see a trend and a standalone project looks like a good solution, while in kernel we can focus on the specimen activation itself.

**Comment by moodmosaic** [comment]
>The benefit will be that we'll be more permissive in accepting the new range support, without worrying that it blows up the AutoFixture. Instead, it will blow up the AutoFixture.DataAnnotations package

I don't understand, what's the difference of having this separately? It'll have the same priority as the AutoFixture package, isn't it?

**Comment by zvirja** [comment]
>  It'll have the same priority as the AutoFixture package, isn't it?

I'm not sure what exactly you mean by the "priority", but yep, that would be first-class citizen in our solution, like any other project.

> I don't understand, what's the difference of having this separately?

Currently I see the following benefits:
- It makes the organization simpler, as you can manage annotation based entities easily and clearly see the boundaries. Currently they are all spread around in the `AutoFixture` project.
- [Continuation] I predict that we'll be more willing to accept features (like support of different range types). Currently I start to worry that if we accept a lot of range related things, it will add a lot of very specific features which might be not useful for anybody. However, if you have a separate project, you shouldn't worry about that - people will install that package only if they wish to work with annotations. As result, even small features could be added there.
- It allows to enable support only if you require that. As result, you will benefit from the performance perspective.
- [Continuation] It allows to not depend on data annotation packages in the AutoFixture project, and do not have those dependencies in your project if you don't use data annotations.

The main benefit I see is the maintenance. The DataAnnotations support looks like a solid unit with clear boundaries with its own dependencies. That's why I see it logical to extract that to a separate project and manage that separately. For now I see that we'll extract 20+ classes there, which is pretty much.

**Comment by zvirja** [comment]
Ok, probably we should disregard that stuff. I've just tried to perform the extraction and found that actually we'll move only 5 classes instead of 20+. Due to some reasons that Xeger could be extracted as well, however that appeared to not be possible. Obviously, it's a super overkill to have a project for 5-10 classes. So let's keep that as is 😉 

Sorry for the time you spent on this.

**Comment by moodmosaic** [comment]
No worries. It's always a pleasure to discuss upfront a potential massive set of changes 😃

**Comment by zvirja** [comment]
Marking this as a potentially new feature.
