### ISSUE TITLE
Customize<T> now uses exact type?

### ISSUE THREAD

**Issue by 7Pass** [AutoFixture/AutoFixture#974]
I've just upgraded my code base to AutoFixture 4. Everything looks good except one that Customize<T> now uses exact type instead of also applying to inherited types. I'd suggest that we add this to the release notes.

Is there anyway to use Customize that also applies to inherited classes with version 4?
Great thanks to those continuing to support AutoFixture, it's a must have for my unit testing.

**Comment by zvirja** [comment]
It seems that we need to create a separate section in the Release Notes for this change, as you are not the first one who asks about that (e.g. see #966) 😅

In fact fixture customization never fully supported the inheritance. Rather, we had a particularity of the implementation, so that `fixture.Customize<MyType>(c => c.Without(x => x.Prop))` seemed to work. That particularity leaded to the inconsistency and weird behavior (see e.g. #772). Therefore, [I've reworked](781) how the customization works, so now there is a complete isolation between the types.

This change is briefly mentioned in the release notes ([see](https://github.com/AutoFixture/AutoFixture/wiki/v4.0-Release-Notes#bug-fixes-) `Fix one customization could affect other customizations`). In fact that was a regular bug fix, rather than a feature, that's why I haven't described that in detail.

> Is there anyway to use Customize that also applies to inherited classes with version 4?

If your goal is to skip setup for the particular properties, than you can follow the approach described [here](https://github.com/AutoFixture/AutoFixture/issues/966#issuecomment-357668852). You can create an own extension method if you need to do that frequently. If you have a different scenario - please describe it.

**Comment by 7Pass** [comment]
Thanks for the feedback. I did look at the `Fix one customization could affect other customizations` but did not fully understand. I'm in support of the change and that you spent the time to improve the project. I just think that 4.0 release notes may need a bit more information as you've shown.

By the way, I think I've encountered another bug, in which `IFixture.Build<T>()` loses some customizations that works with `IFixture.Create<T>()`. I'll find sometime to create a reproduction and create a separate issue to report it.
