### ISSUE TITLE
Return really read-only collections for `IReadOnlyList<>` and `IReadOnlyCollection<>`

### ISSUE THREAD

**Issue by zvirja** [AutoFixture/AutoFixture#981]
Currently we return writable collections for the mentioned interfaces. Ensure that we construct read-only collections for those interfaces. It could help to catch tricky issues with user code.

@moodmosaic I believe that we don't need a next major for this change and can release it in the next feature/bug-fix release. Do you agree? :)

**Comment by Kralizek** [comment]
Preparing a fix for this (guilty feeling as I am the one introducing the bug)

I don't think it should be a major since the collection is returned by the requested interface. Which type is actually returned shouldn't matter. Unless someone reflected upon the returned type, but it would be quite an awkward use case.

**Comment by moodmosaic** [comment]
This looks more like a bug, because we're asking for a read-only collection, but we're getting back one of a different type.

However, if the test(s) reflect that... then it's actually a change in the public API, and so we can consider doing releasing it as part of the next minor version.
